"""063 align schema drift

Revision ID: 265c4ea55361
Revises: 062
Create Date: 2026-08-16 19:54:13.427685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '063'
down_revision: Union[str, None] = '062'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_audit_event_time', table_name='audit_operation_log')
    op.drop_index('ix_audit_event_type', table_name='audit_operation_log')
    op.drop_index('ix_audit_request_id', table_name='audit_operation_log')
    op.drop_index('ix_audit_resource', table_name='audit_operation_log')
    op.drop_index('ix_audit_user_event', table_name='audit_operation_log')
    op.create_index(op.f('ix_audit_operation_log_event_time'), 'audit_operation_log', ['event_time'], unique=False)
    op.create_index(op.f('ix_audit_operation_log_event_type'), 'audit_operation_log', ['event_type'], unique=False)
    op.create_index(op.f('ix_audit_operation_log_log_id'), 'audit_operation_log', ['log_id'], unique=False)
    op.create_index(op.f('ix_audit_operation_log_request_id'), 'audit_operation_log', ['request_id'], unique=False)
    op.create_index(op.f('ix_audit_operation_log_resource_type'), 'audit_operation_log', ['resource_type'], unique=False)
    op.create_index(op.f('ix_audit_operation_log_user_id'), 'audit_operation_log', ['user_id'], unique=False)
    op.alter_column('config_venue', 'h_index',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('config_venue', 'works_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('config_venue', 'cited_by_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('config_venue', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('config_venue', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('config_venue_openalex_source_id_key', 'config_venue', type_='unique')
    op.drop_constraint('config_venue_venue_code_key', 'config_venue', type_='unique')
    op.drop_index('ix_config_venue_code', table_name='config_venue')
    op.drop_index('ix_config_venue_name', table_name='config_venue')
    op.drop_index('ix_config_venue_openalex_id', table_name='config_venue')
    op.drop_index('ix_config_venue_type', table_name='config_venue')
    op.create_index(op.f('ix_config_venue_openalex_source_id'), 'config_venue', ['openalex_source_id'], unique=True)
    op.create_index(op.f('ix_config_venue_venue_code'), 'config_venue', ['venue_code'], unique=True)
    op.create_index(op.f('ix_config_venue_venue_id'), 'config_venue', ['venue_id'], unique=False)
    op.alter_column('config_venue_tech_binding', 'priority',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('config_venue_tech_binding', 'author_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('config_venue_tech_binding', 'work_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('config_venue_tech_binding', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('config_venue_tech_binding', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_venue_binding_status', table_name='config_venue_tech_binding')
    op.drop_index('ix_venue_binding_tech', table_name='config_venue_tech_binding')
    op.drop_index('ix_venue_binding_venue', table_name='config_venue_tech_binding')
    op.create_index(op.f('ix_config_venue_tech_binding_binding_id'), 'config_venue_tech_binding', ['binding_id'], unique=False)
    op.create_index(op.f('ix_config_venue_tech_binding_tech_domain_id'), 'config_venue_tech_binding', ['tech_domain_id'], unique=False)
    op.create_index(op.f('ix_config_venue_tech_binding_venue_id'), 'config_venue_tech_binding', ['venue_id'], unique=False)
    op.alter_column('core_collaboration', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('core_collaboration', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_index('ix_core_collaboration_id', table_name='core_collaboration')
    op.create_index(op.f('ix_core_collaboration_collaboration_id'), 'core_collaboration', ['collaboration_id'], unique=False)
    op.create_foreign_key(None, 'core_collaboration', 'core_talent', ['talent_id_2'], ['talent_id'])
    op.create_foreign_key(None, 'core_collaboration', 'core_talent', ['talent_id_1'], ['talent_id'])
    op.drop_index('ix_core_role_profile_talent_id', table_name='core_role_profile')
    op.create_index(op.f('ix_core_role_profile_profile_id'), 'core_role_profile', ['profile_id'], unique=False)
    op.alter_column('core_school', 'country_code',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.drop_index('ix_core_school_is_top', table_name='core_school')
    op.drop_index('ix_core_school_source_record_id_unique', table_name='core_school')
    op.drop_index('ix_core_school_status_visible', table_name='core_school')
    op.drop_index('ix_core_school_source_record_id', table_name='core_school')
    op.create_index(op.f('ix_core_school_source_record_id'), 'core_school', ['source_record_id'], unique=True)
    op.create_index(op.f('ix_core_school_is_top_school'), 'core_school', ['is_top_school'], unique=False)
    op.create_index(op.f('ix_core_school_school_id'), 'core_school', ['school_id'], unique=False)
    op.create_index(op.f('ix_core_school_alias_alias_id'), 'core_school_alias', ['alias_id'], unique=False)
    op.create_index(op.f('ix_core_selected_work_work_id'), 'core_selected_work', ['work_id'], unique=False)
    op.execute("ALTER TABLE core_talent ALTER COLUMN topic_tags TYPE JSONB USING topic_tags::text::jsonb")
    op.drop_index('ix_core_talent_cited_by_count', table_name='core_talent')
    op.drop_index('ix_core_talent_h_index', table_name='core_talent')
    op.drop_index('ix_core_talent_openalex_topics_gin', table_name='core_talent', postgresql_using='gin', postgresql_where='(openalex_topics IS NOT NULL)')
    op.drop_index('ix_core_talent_openalex_topics_trgm', table_name='core_talent', postgresql_using='gin', postgresql_where='(openalex_topics IS NOT NULL)')
    op.drop_index('ix_core_talent_school_role', table_name='core_talent')
    op.drop_index('ix_core_talent_source_record_id_unique', table_name='core_talent')
    op.drop_index('ix_core_talent_std_author', table_name='core_talent')
    op.drop_index('ix_core_talent_visible_cited_desc', table_name='core_talent')
    op.drop_index('ix_core_talent_visible_school_role', table_name='core_talent')
    op.drop_index('ix_core_talent_works_count', table_name='core_talent')
    op.drop_index('ix_talent_company_school', table_name='core_talent')
    op.drop_index('ix_talent_education_school', table_name='core_talent')
    op.drop_index('ix_core_talent_source_record_id', table_name='core_talent')
    op.create_index(op.f('ix_core_talent_source_record_id'), 'core_talent', ['source_record_id'], unique=True)
    op.create_index(op.f('ix_core_talent_company_school_id'), 'core_talent', ['company_school_id'], unique=False)
    op.create_index(op.f('ix_core_talent_education_school_id'), 'core_talent', ['education_school_id'], unique=False)
    op.create_index(op.f('ix_core_talent_std_author_id'), 'core_talent', ['std_author_id'], unique=False)
    op.create_index(op.f('ix_core_talent_talent_id'), 'core_talent', ['talent_id'], unique=False)
    op.alter_column('core_talent_embedding', 'talent_id',
               existing_type=sa.INTEGER(),
               comment='关联人才ID',
               existing_nullable=False)
    op.alter_column('core_talent_embedding', 'vector_type',
               existing_type=sa.VARCHAR(length=20),
               comment='向量类型: research(研究方向) / papers(论文标题)',
               existing_nullable=False,
               existing_server_default=sa.text("'research'::character varying"))
    op.alter_column('core_talent_embedding', 'embedding',
               existing_type=postgresql.JSONB(),
               comment='向量嵌入 (JSON或pgvector)',
               existing_nullable=False)
    op.alter_column('core_talent_embedding', 'model_name',
               existing_type=sa.VARCHAR(length=100),
               comment='嵌入模型名称',
               existing_nullable=False)
    op.alter_column('core_talent_embedding', 'source_text_hash',
               existing_type=sa.VARCHAR(length=64),
               comment='源文本哈希，用于判断是否需要更新',
               existing_nullable=False)
    op.drop_index('ix_embedding_papers', table_name='core_talent_embedding', postgresql_with={'lists': '100'}, postgresql_using='ivfflat', postgresql_where="((vector_type)::text = 'papers'::text)")
    op.drop_index('ix_embedding_research', table_name='core_talent_embedding', postgresql_with={'lists': '100'}, postgresql_using='ivfflat', postgresql_where="((vector_type)::text = 'research'::text)")
    op.drop_index('ix_embedding_vector_type', table_name='core_talent_embedding')
    op.drop_index('ix_talent_embedding_model', table_name='core_talent_embedding')
    op.create_index(op.f('ix_core_talent_embedding_talent_id'), 'core_talent_embedding', ['talent_id'], unique=False)
    op.create_index(op.f('ix_core_talent_embedding_vector_type'), 'core_talent_embedding', ['vector_type'], unique=False)
    op.drop_index('ix_talent_tech_enabled_direction', table_name='core_talent_tech_tag', postgresql_where='(is_enabled = true)')
    op.drop_index('ix_talent_tech_enabled_domain', table_name='core_talent_tech_tag', postgresql_where='(is_enabled = true)')
    op.drop_index('ix_talent_tech_tag_direction', table_name='core_talent_tech_tag')
    op.drop_index('ix_talent_tech_tag_domain', table_name='core_talent_tech_tag')
    op.drop_index('ix_talent_tech_tag_enabled', table_name='core_talent_tech_tag')
    op.drop_index('ix_talent_tech_tag_talent', table_name='core_talent_tech_tag')
    op.create_index(op.f('ix_core_talent_tech_tag_tag_id'), 'core_talent_tech_tag', ['tag_id'], unique=False)
    op.create_index(op.f('ix_core_talent_tech_tag_talent_id'), 'core_talent_tech_tag', ['talent_id'], unique=False)
    op.create_index(op.f('ix_core_talent_tech_tag_tech_direction_id'), 'core_talent_tech_tag', ['tech_direction_id'], unique=False)
    op.create_index(op.f('ix_core_talent_tech_tag_tech_domain_id'), 'core_talent_tech_tag', ['tech_domain_id'], unique=False)
    op.drop_index('ix_tech_direction_code', table_name='core_tech_direction')
    op.drop_index('ix_tech_direction_domain', table_name='core_tech_direction')
    op.drop_index('ix_tech_direction_enabled', table_name='core_tech_direction')
    op.create_index(op.f('ix_core_tech_direction_tech_direction_id'), 'core_tech_direction', ['tech_direction_id'], unique=False)
    op.create_index(op.f('ix_core_tech_direction_tech_domain_id'), 'core_tech_direction', ['tech_domain_id'], unique=False)
    op.drop_index('ix_tech_element_code', table_name='core_tech_domain')
    op.drop_index('ix_tech_element_enabled', table_name='core_tech_domain')
    op.create_index(op.f('ix_core_tech_domain_tech_domain_id'), 'core_tech_domain', ['tech_domain_id'], unique=False)
    op.alter_column('core_work_author', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('core_work_author', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_index('ix_core_work_author_id', table_name='core_work_author')
    op.create_index(op.f('ix_core_work_author_work_author_id'), 'core_work_author', ['work_author_id'], unique=False)
    op.create_foreign_key(None, 'core_work_author', 'core_talent', ['talent_id'], ['talent_id'])
    op.drop_index('ix_correction_status', table_name='data_correction_record')
    op.drop_index('ix_correction_target', table_name='data_correction_record')
    op.create_index(op.f('ix_data_correction_record_correction_id'), 'data_correction_record', ['correction_id'], unique=False)
    op.create_index(op.f('ix_data_correction_record_target_id'), 'data_correction_record', ['target_id'], unique=False)
    op.create_index(op.f('ix_data_correction_record_target_type'), 'data_correction_record', ['target_type'], unique=False)
    op.drop_index('ix_publish_record_version', table_name='data_publish_record')
    op.create_index(op.f('ix_data_publish_record_publish_id'), 'data_publish_record', ['publish_id'], unique=False)
    op.create_index(op.f('ix_data_publish_record_version_id'), 'data_publish_record', ['version_id'], unique=False)
    op.drop_index('ix_quality_summary_date', table_name='data_quality_summary')
    op.drop_index('ix_quality_summary_version', table_name='data_quality_summary')
    op.create_index(op.f('ix_data_quality_summary_summary_date'), 'data_quality_summary', ['summary_date'], unique=False)
    op.create_index(op.f('ix_data_quality_summary_summary_id'), 'data_quality_summary', ['summary_id'], unique=False)
    op.create_index(op.f('ix_data_quality_summary_version_id'), 'data_quality_summary', ['version_id'], unique=False)
    op.drop_constraint('data_version_version_code_key', 'data_version', type_='unique')
    op.drop_index('ix_data_version_active', table_name='data_version')
    op.drop_index('ix_data_version_code', table_name='data_version')
    op.create_index(op.f('ix_data_version_is_active'), 'data_version', ['is_active'], unique=False)
    op.create_index(op.f('ix_data_version_version_code'), 'data_version', ['version_code'], unique=True)
    op.create_index(op.f('ix_data_version_version_id'), 'data_version', ['version_id'], unique=False)
    op.drop_index('ix_genealogy_edge_confidence', table_name='genealogy_edge')
    op.drop_index('ix_favorite_user_active_created', table_name='iam_favorite_talent', postgresql_where='(is_active = true)')
    op.drop_index('ix_iam_favorite_is_active', table_name='iam_favorite_talent')
    op.drop_index('ix_iam_favorite_talent_id', table_name='iam_favorite_talent')
    op.drop_index('ix_iam_favorite_user_id', table_name='iam_favorite_talent')
    op.create_index(op.f('ix_iam_favorite_talent_favorite_id'), 'iam_favorite_talent', ['favorite_id'], unique=False)
    op.create_index(op.f('ix_iam_favorite_talent_talent_id'), 'iam_favorite_talent', ['talent_id'], unique=False)
    op.create_index(op.f('ix_iam_favorite_talent_user_id'), 'iam_favorite_talent', ['user_id'], unique=False)
    op.drop_index('ix_talent_pool_owner', table_name='iam_talent_pool')
    op.drop_index('ix_talent_pool_status', table_name='iam_talent_pool')
    op.create_index(op.f('ix_iam_talent_pool_owner_user_id'), 'iam_talent_pool', ['owner_user_id'], unique=False)
    op.create_index(op.f('ix_iam_talent_pool_pool_id'), 'iam_talent_pool', ['pool_id'], unique=False)
    op.drop_index('ix_pool_member_pool', table_name='iam_talent_pool_member')
    op.drop_index('ix_pool_member_talent', table_name='iam_talent_pool_member')
    op.create_index(op.f('ix_iam_talent_pool_member_member_id'), 'iam_talent_pool_member', ['member_id'], unique=False)
    op.create_index(op.f('ix_iam_talent_pool_member_pool_id'), 'iam_talent_pool_member', ['pool_id'], unique=False)
    op.create_index(op.f('ix_iam_talent_pool_member_talent_id'), 'iam_talent_pool_member', ['talent_id'], unique=False)
    op.drop_constraint('iam_user_account_email_key', 'iam_user_account', type_='unique')
    op.drop_constraint('iam_user_account_username_key', 'iam_user_account', type_='unique')
    op.drop_index('ix_iam_user_account_created_at', table_name='iam_user_account')
    op.drop_index('ix_iam_user_email', table_name='iam_user_account')
    op.drop_index('ix_iam_user_username', table_name='iam_user_account')
    op.drop_index('ix_user_account_employee_id', table_name='iam_user_account')
    op.create_index(op.f('ix_iam_user_account_email'), 'iam_user_account', ['email'], unique=True)
    op.create_index(op.f('ix_iam_user_account_employee_id'), 'iam_user_account', ['employee_id'], unique=True)
    op.create_index(op.f('ix_iam_user_account_user_id'), 'iam_user_account', ['user_id'], unique=False)
    op.create_index(op.f('ix_iam_user_account_username'), 'iam_user_account', ['username'], unique=True)
    op.drop_index('ix_iam_scope_type_value', table_name='iam_user_school_scope')
    op.drop_index('ix_iam_scope_user_id', table_name='iam_user_school_scope')
    op.drop_constraint('uq_user_scope', 'iam_user_school_scope', type_='unique')
    op.create_index(op.f('ix_iam_user_school_scope_scope_id'), 'iam_user_school_scope', ['scope_id'], unique=False)
    op.create_index(op.f('ix_iam_user_school_scope_user_id'), 'iam_user_school_scope', ['user_id'], unique=False)
    op.drop_constraint('industry_talent_dedup_hash_key', 'industry_talent', type_='unique')
    op.drop_index('ix_industry_talent_dedup_hash', table_name='industry_talent')
    op.create_index(op.f('ix_industry_talent_dedup_hash'), 'industry_talent', ['dedup_hash'], unique=True)
    op.alter_column('jd_match_result', 'session_id',
               existing_type=sa.INTEGER(),
               comment='会话ID',
               existing_nullable=False)
    op.alter_column('jd_match_result', 'talent_id',
               existing_type=sa.INTEGER(),
               comment='人才ID',
               existing_nullable=False)
    op.alter_column('jd_match_result', 'overall_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='综合匹配分数 0-100',
               existing_nullable=True)
    op.alter_column('jd_match_result', 'skill_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='技能匹配分数',
               existing_nullable=True)
    op.alter_column('jd_match_result', 'research_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='研究方向匹配分数',
               existing_nullable=True)
    op.alter_column('jd_match_result', 'experience_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='经验匹配分数',
               existing_nullable=True)
    op.alter_column('jd_match_result', 'match_reasons',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='匹配原因列表',
               existing_nullable=True)
    op.alter_column('jd_match_result', 'highlight_skills',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='匹配的技能列表',
               existing_nullable=True)
    op.alter_column('jd_match_result', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_index('ix_jd_match_result_score', table_name='jd_match_result')
    op.drop_index('ix_jd_match_result_session', table_name='jd_match_result')
    op.drop_index('ix_jd_match_result_talent', table_name='jd_match_result')
    op.create_index(op.f('ix_jd_match_result_session_id'), 'jd_match_result', ['session_id'], unique=False)
    op.create_index(op.f('ix_jd_match_result_talent_id'), 'jd_match_result', ['talent_id'], unique=False)
    op.alter_column('jd_match_session', 'user_id',
               existing_type=sa.INTEGER(),
               comment='用户ID',
               existing_nullable=False)
    op.alter_column('jd_match_session', 'jd_text',
               existing_type=sa.TEXT(),
               comment='原始 JD 文本',
               existing_nullable=False)
    op.alter_column('jd_match_session', 'jd_features',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='LLM 解析出的 JD 特征',
               existing_nullable=True)
    op.alter_column('jd_match_session', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment='状态: pending/completed/failed',
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('jd_match_session', 'completed_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='完成时间',
               existing_nullable=True)
    op.alter_column('jd_match_session', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_index('ix_jd_match_session_created', table_name='jd_match_session')
    op.drop_index('ix_jd_match_session_user', table_name='jd_match_session')
    op.create_index(op.f('ix_jd_match_session_user_id'), 'jd_match_session', ['user_id'], unique=False)
    op.drop_index('ix_lab_info_lab_info_id', table_name='lab_info')
    op.drop_constraint('uq_lab_info_parent_lab', 'lab_info', type_='unique')
    op.drop_index('ix_lab_talent_advisor', table_name='lab_talent')
    op.drop_constraint('uq_lab_talent_dedup_hash', 'lab_talent', type_='unique')
    op.drop_index('ix_os_collect_task_created_at', table_name='os_collect_task')
    op.create_index(op.f('ix_os_collect_task_task_id'), 'os_collect_task', ['task_id'], unique=False)
    op.drop_index('ix_os_contribution_dev_id', table_name='os_contribution')
    op.drop_index('ix_os_contribution_dev_repo', table_name='os_contribution')
    op.create_index(op.f('ix_os_contribution_contribution_id'), 'os_contribution', ['contribution_id'], unique=False)
    op.create_index(op.f('ix_os_contribution_developer_id'), 'os_contribution', ['developer_id'], unique=False)
    op.drop_index('ix_os_developer_bio_trgm', table_name='os_developer', postgresql_using='gin')
    op.drop_index('ix_os_developer_company', table_name='os_developer')
    op.drop_index('ix_os_developer_company_trgm', table_name='os_developer', postgresql_using='gin')
    op.drop_index('ix_os_developer_github_login_trgm', table_name='os_developer', postgresql_using='gin')
    op.drop_index('ix_os_developer_location', table_name='os_developer')
    op.drop_index('ix_os_developer_location_trgm', table_name='os_developer', postgresql_using='gin')
    op.drop_index('ix_os_developer_name_trgm', table_name='os_developer', postgresql_using='gin')
    op.drop_index('ix_os_developer_primary_languages_gin', table_name='os_developer', postgresql_using='gin')
    op.drop_index('ix_os_developer_stars_desc', table_name='os_developer')
    op.drop_index('ix_os_developer_tech_tags_gin', table_name='os_developer', postgresql_using='gin')
    op.drop_index('ix_os_developer_visible', table_name='os_developer')
    op.create_index(op.f('ix_os_developer_developer_id'), 'os_developer', ['developer_id'], unique=False)
    op.create_index(op.f('ix_os_developer_github_id'), 'os_developer', ['github_id'], unique=True)
    op.drop_index('ix_os_embedding_dev_type', table_name='os_embedding')
    op.drop_index('ix_os_embedding_hash', table_name='os_embedding')
    op.drop_index('ix_os_embedding_vector', table_name='os_embedding', postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.create_index(op.f('ix_os_embedding_embedding_id'), 'os_embedding', ['embedding_id'], unique=False)
    op.create_index(op.f('ix_os_embedding_source_text_hash'), 'os_embedding', ['source_text_hash'], unique=False)
    op.drop_index('ix_os_favourite_user_dev', table_name='os_favourite')
    op.create_index(op.f('ix_os_favourite_favourite_id'), 'os_favourite', ['favourite_id'], unique=False)
    op.drop_index('ix_os_language_skill_dev_id', table_name='os_language_skill')
    op.drop_index('ix_os_language_skill_dev_lang', table_name='os_language_skill')
    op.create_index(op.f('ix_os_language_skill_developer_id'), 'os_language_skill', ['developer_id'], unique=False)
    op.create_index(op.f('ix_os_language_skill_skill_id'), 'os_language_skill', ['skill_id'], unique=False)
    op.drop_index('ix_os_pool_member_pool_dev', table_name='os_pool_member')
    op.create_index(op.f('ix_os_pool_member_pool_member_id'), 'os_pool_member', ['pool_member_id'], unique=False)
    op.drop_index('ix_os_raw_developer_login', table_name='os_raw_developer')
    op.create_index(op.f('ix_os_raw_developer_github_login'), 'os_raw_developer', ['github_login'], unique=False)
    op.create_index(op.f('ix_os_raw_developer_raw_id'), 'os_raw_developer', ['raw_id'], unique=False)
    op.alter_column('os_repo_config', 'tech_element',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.drop_index('ix_os_repo_config_collect', table_name='os_repo_config')
    op.drop_index('ix_os_repo_config_tech_element', table_name='os_repo_config', postgresql_using='gin')
    op.create_index(op.f('ix_os_repo_config_repo_config_id'), 'os_repo_config', ['repo_config_id'], unique=False)
    op.drop_index('ix_os_repo_mapping_repo', table_name='os_repo_mapping')
    op.create_index(op.f('ix_os_repo_mapping_mapping_id'), 'os_repo_mapping', ['mapping_id'], unique=False)
    op.create_index(op.f('ix_os_repo_mapping_repo_full_name'), 'os_repo_mapping', ['repo_full_name'], unique=False)
    op.drop_index('ix_os_repository_dev_id', table_name='os_repository')
    op.drop_index('ix_os_repository_full_name', table_name='os_repository')
    op.drop_index('ix_os_repository_github_id', table_name='os_repository')
    op.drop_index('ix_os_repository_stars', table_name='os_repository')
    op.create_index(op.f('ix_os_repository_developer_id'), 'os_repository', ['developer_id'], unique=False)
    op.create_index(op.f('ix_os_repository_github_repo_id'), 'os_repository', ['github_repo_id'], unique=False)
    op.create_index(op.f('ix_os_repository_repo_id'), 'os_repository', ['repo_id'], unique=False)
    op.create_unique_constraint(None, 'os_repository', ['full_name'])
    op.drop_index('ix_os_talent_pool_owner', table_name='os_talent_pool')
    op.create_index(op.f('ix_os_talent_pool_owner_user_id'), 'os_talent_pool', ['owner_user_id'], unique=False)
    op.create_index(op.f('ix_os_talent_pool_pool_id'), 'os_talent_pool', ['pool_id'], unique=False)
    op.alter_column('raw_author', 'works_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('raw_author', 'cited_by_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('raw_author', 'h_index',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('raw_author', 'i10_index',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('raw_author', 'processed_status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('raw_author', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('raw_author', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_raw_author_fetch_task_id', table_name='raw_author')
    op.drop_index('ix_raw_author_inst', table_name='raw_author')
    op.drop_index('ix_raw_author_name', table_name='raw_author')
    op.drop_index('ix_raw_author_openalex', table_name='raw_author')
    op.drop_index('ix_raw_author_status', table_name='raw_author')
    op.drop_index('ix_raw_author_status_task', table_name='raw_author')
    op.drop_index('ix_raw_author_std', table_name='raw_author')
    op.drop_constraint('raw_author_openalex_author_id_key', 'raw_author', type_='unique')
    op.create_index(op.f('ix_raw_author_display_name'), 'raw_author', ['display_name'], unique=False)
    op.create_index(op.f('ix_raw_author_last_known_institution_id'), 'raw_author', ['last_known_institution_id'], unique=False)
    op.create_index(op.f('ix_raw_author_openalex_author_id'), 'raw_author', ['openalex_author_id'], unique=True)
    op.create_index(op.f('ix_raw_author_processed_status'), 'raw_author', ['processed_status'], unique=False)
    op.create_index(op.f('ix_raw_author_raw_author_id'), 'raw_author', ['raw_author_id'], unique=False)
    op.create_index(op.f('ix_raw_author_std_author_id'), 'raw_author', ['std_author_id'], unique=False)
    op.alter_column('raw_institution', 'processed_status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('raw_institution', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('raw_institution', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_raw_inst_country', table_name='raw_institution')
    op.drop_index('ix_raw_inst_name', table_name='raw_institution')
    op.drop_index('ix_raw_inst_openalex', table_name='raw_institution')
    op.drop_index('ix_raw_inst_status', table_name='raw_institution')
    op.drop_index('ix_raw_inst_status_task', table_name='raw_institution')
    op.drop_index('ix_raw_inst_std', table_name='raw_institution')
    op.drop_constraint('raw_institution_openalex_institution_id_key', 'raw_institution', type_='unique')
    op.create_index(op.f('ix_raw_institution_country_code'), 'raw_institution', ['country_code'], unique=False)
    op.create_index(op.f('ix_raw_institution_display_name'), 'raw_institution', ['display_name'], unique=False)
    op.create_index(op.f('ix_raw_institution_openalex_institution_id'), 'raw_institution', ['openalex_institution_id'], unique=True)
    op.create_index(op.f('ix_raw_institution_processed_status'), 'raw_institution', ['processed_status'], unique=False)
    op.create_index(op.f('ix_raw_institution_raw_institution_id'), 'raw_institution', ['raw_institution_id'], unique=False)
    op.create_index(op.f('ix_raw_institution_std_school_id'), 'raw_institution', ['std_school_id'], unique=False)
    op.alter_column('raw_work', 'author_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('raw_work', 'processed_status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('raw_work', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('raw_work', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_raw_work_fetch_task_id', table_name='raw_work')
    op.drop_index('ix_raw_work_openalex', table_name='raw_work')
    op.drop_index('ix_raw_work_source', table_name='raw_work')
    op.drop_index('ix_raw_work_source_year', table_name='raw_work')
    op.drop_index('ix_raw_work_status', table_name='raw_work')
    op.drop_index('ix_raw_work_sub_task_id', table_name='raw_work')
    op.drop_index('ix_raw_work_title_trgm', table_name='raw_work', postgresql_using='gin', postgresql_where='(title IS NOT NULL)')
    op.drop_index('ix_raw_work_year', table_name='raw_work')
    op.drop_constraint('raw_work_openalex_work_id_key', 'raw_work', type_='unique')
    op.create_index(op.f('ix_raw_work_openalex_work_id'), 'raw_work', ['openalex_work_id'], unique=True)
    op.create_index(op.f('ix_raw_work_processed_status'), 'raw_work', ['processed_status'], unique=False)
    op.create_index(op.f('ix_raw_work_publication_year'), 'raw_work', ['publication_year'], unique=False)
    op.create_index(op.f('ix_raw_work_raw_work_id'), 'raw_work', ['raw_work_id'], unique=False)
    op.create_index(op.f('ix_raw_work_source_id'), 'raw_work', ['source_id'], unique=False)
    op.alter_column('rel_author_tech_belong', 'work_count_in_venue',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('rel_author_tech_belong', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('rel_author_tech_belong', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_author_tech_author', table_name='rel_author_tech_belong')
    op.drop_index('ix_author_tech_domain', table_name='rel_author_tech_belong')
    op.drop_index('ix_author_tech_venue', table_name='rel_author_tech_belong')
    op.drop_index('ix_rel_author_tech_belong_source_task_id', table_name='rel_author_tech_belong')
    op.drop_index('ix_rel_author_tech_belong_source_venue_id', table_name='rel_author_tech_belong')
    op.create_index(op.f('ix_rel_author_tech_belong_belong_id'), 'rel_author_tech_belong', ['belong_id'], unique=False)
    op.create_index(op.f('ix_rel_author_tech_belong_openalex_author_id'), 'rel_author_tech_belong', ['openalex_author_id'], unique=False)
    op.create_index(op.f('ix_rel_author_tech_belong_std_author_id'), 'rel_author_tech_belong', ['std_author_id'], unique=False)
    op.create_index(op.f('ix_rel_author_tech_belong_tech_domain_id'), 'rel_author_tech_belong', ['tech_domain_id'], unique=False)
    op.execute("ALTER TABLE search_talent_document ALTER COLUMN topic_tags TYPE JSONB USING to_jsonb(topic_tags::text[])")
    op.drop_index('ix_search_active', table_name='search_talent_document')
    op.drop_index('ix_search_country_code', table_name='search_talent_document')
    op.drop_index('ix_search_role_type', table_name='search_talent_document')
    op.drop_index('ix_search_school_id', table_name='search_talent_document')
    op.drop_index('ix_search_talent_document_name_trgm', table_name='search_talent_document', postgresql_using='gin')
    op.drop_index('ix_search_talent_document_vector', table_name='search_talent_document', postgresql_using='gin')
    op.drop_index('ix_search_talent_id', table_name='search_talent_document')
    op.drop_index('ix_search_text', table_name='search_talent_document', postgresql_using='gin')
    op.drop_constraint('search_talent_document_talent_id_key', 'search_talent_document', type_='unique')
    op.create_index(op.f('ix_search_talent_document_country_code'), 'search_talent_document', ['country_code'], unique=False)
    op.create_index(op.f('ix_search_talent_document_document_id'), 'search_talent_document', ['document_id'], unique=False)
    op.create_index(op.f('ix_search_talent_document_is_active'), 'search_talent_document', ['is_active'], unique=False)
    op.create_index(op.f('ix_search_talent_document_role_type'), 'search_talent_document', ['role_type'], unique=False)
    op.create_index(op.f('ix_search_talent_document_school_id'), 'search_talent_document', ['school_id'], unique=False)
    op.create_index(op.f('ix_search_talent_document_talent_id'), 'search_talent_document', ['talent_id'], unique=True)
    op.drop_index('ix_stat_overview_version', table_name='stat_overview_snapshot')
    op.create_index(op.f('ix_stat_overview_snapshot_snapshot_id'), 'stat_overview_snapshot', ['snapshot_id'], unique=False)
    op.create_index(op.f('ix_stat_overview_snapshot_stat_version'), 'stat_overview_snapshot', ['stat_version'], unique=False)
    op.drop_index('ix_stat_school_snapshot_version', table_name='stat_school_snapshot')
    op.create_index(op.f('ix_stat_school_snapshot_snapshot_id'), 'stat_school_snapshot', ['snapshot_id'], unique=False)
    op.create_index(op.f('ix_stat_school_snapshot_stat_version'), 'stat_school_snapshot', ['stat_version'], unique=False)
    op.alter_column('stats_research_topic', 'talent_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index('ix_stats_research_topic_count', table_name='stats_research_topic')
    op.alter_column('std_author', 'works_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('std_author', 'cited_by_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('std_author', 'h_index',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('std_author', 'i10_index',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('std_author', 'confidence_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text("'0.8'::double precision"))
    op.alter_column('std_author', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('std_author', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_std_author_name', table_name='std_author')
    op.drop_index('ix_std_author_openalex', table_name='std_author')
    op.drop_index('ix_std_author_school', table_name='std_author')
    op.drop_index('ix_std_author_status', table_name='std_author')
    op.drop_constraint('std_author_openalex_author_id_key', 'std_author', type_='unique')
    op.create_index(op.f('ix_std_author_confirm_status'), 'std_author', ['confirm_status'], unique=False)
    op.create_index(op.f('ix_std_author_name_normalized'), 'std_author', ['name_normalized'], unique=False)
    op.create_index(op.f('ix_std_author_openalex_author_id'), 'std_author', ['openalex_author_id'], unique=True)
    op.create_index(op.f('ix_std_author_std_author_id'), 'std_author', ['std_author_id'], unique=False)
    op.create_index(op.f('ix_std_author_std_school_id'), 'std_author', ['std_school_id'], unique=False)
    op.create_foreign_key(None, 'std_author', 'sync_collect_task', ['source_task_id'], ['task_id'])
    op.alter_column('std_school', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('std_school', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_std_school_name', table_name='std_school')
    op.drop_index('ix_std_school_openalex', table_name='std_school')
    op.drop_index('ix_std_school_school', table_name='std_school')
    op.drop_index('ix_std_school_status', table_name='std_school')
    op.drop_constraint('std_school_openalex_institution_id_key', 'std_school', type_='unique')
    op.create_index(op.f('ix_std_school_confirm_status'), 'std_school', ['confirm_status'], unique=False)
    op.create_index(op.f('ix_std_school_name_normalized'), 'std_school', ['name_normalized'], unique=False)
    op.create_index(op.f('ix_std_school_openalex_institution_id'), 'std_school', ['openalex_institution_id'], unique=True)
    op.create_index(op.f('ix_std_school_ror'), 'std_school', ['ror'], unique=False)
    op.create_index(op.f('ix_std_school_school_id'), 'std_school', ['school_id'], unique=False)
    op.create_index(op.f('ix_std_school_std_school_id'), 'std_school', ['std_school_id'], unique=False)
    op.create_foreign_key(None, 'std_school', 'sync_collect_task', ['source_task_id'], ['task_id'])
    op.alter_column('std_school_alias', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('std_school_alias', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_school_alias_std', table_name='std_school_alias')
    op.create_index(op.f('ix_std_school_alias_alias_id'), 'std_school_alias', ['alias_id'], unique=False)
    op.create_index(op.f('ix_std_school_alias_alias_name'), 'std_school_alias', ['alias_name'], unique=False)
    op.create_index(op.f('ix_std_school_alias_std_school_id'), 'std_school_alias', ['std_school_id'], unique=False)
    op.add_column('sync_batch', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('sync_batch', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.drop_index('ix_sync_batch_code', table_name='sync_batch')
    op.drop_constraint('sync_batch_batch_code_key', 'sync_batch', type_='unique')
    op.create_index(op.f('ix_sync_batch_batch_code'), 'sync_batch', ['batch_code'], unique=True)
    op.create_index(op.f('ix_sync_batch_batch_id'), 'sync_batch', ['batch_id'], unique=False)
    op.drop_index('ix_collect_scope_code', table_name='sync_collect_scope')
    op.drop_index('ix_collect_scope_type', table_name='sync_collect_scope')
    op.drop_constraint('sync_collect_scope_scope_code_key', 'sync_collect_scope', type_='unique')
    op.create_index(op.f('ix_sync_collect_scope_scope_code'), 'sync_collect_scope', ['scope_code'], unique=True)
    op.create_index(op.f('ix_sync_collect_scope_scope_id'), 'sync_collect_scope', ['scope_id'], unique=False)
    op.drop_index('ix_collect_strategy_code', table_name='sync_collect_strategy')
    op.drop_index('ix_collect_strategy_type', table_name='sync_collect_strategy')
    op.drop_constraint('sync_collect_strategy_strategy_code_key', 'sync_collect_strategy', type_='unique')
    op.create_index(op.f('ix_sync_collect_strategy_strategy_code'), 'sync_collect_strategy', ['strategy_code'], unique=True)
    op.create_index(op.f('ix_sync_collect_strategy_strategy_id'), 'sync_collect_strategy', ['strategy_id'], unique=False)
    op.alter_column('sync_collect_task', 'collect_mode',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'full'::character varying"))
    op.execute("ALTER TABLE sync_collect_task ALTER COLUMN error_details TYPE JSONB USING error_details::text::jsonb")
    op.drop_index('ix_collect_task_code', table_name='sync_collect_task')
    op.drop_index('ix_collect_task_status', table_name='sync_collect_task')
    op.drop_index('ix_collect_task_strategy', table_name='sync_collect_task')
    op.drop_constraint('sync_collect_task_task_code_key', 'sync_collect_task', type_='unique')
    op.create_index(op.f('ix_sync_collect_task_status'), 'sync_collect_task', ['status'], unique=False)
    op.create_index(op.f('ix_sync_collect_task_task_code'), 'sync_collect_task', ['task_code'], unique=True)
    op.create_index(op.f('ix_sync_collect_task_task_id'), 'sync_collect_task', ['task_id'], unique=False)
    op.drop_constraint('sync_collect_task_strategy_id_fkey', 'sync_collect_task', type_='foreignkey')
    op.alter_column('sync_venue_sub_task', 'works_fetched',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('sync_venue_sub_task', 'authors_fetched',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('sync_venue_sub_task', 'new_authors',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('sync_venue_sub_task', 'updated_authors',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('sync_venue_sub_task', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('sync_venue_sub_task', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_venue_sub_task_status', table_name='sync_venue_sub_task')
    op.drop_index('ix_venue_sub_task_task', table_name='sync_venue_sub_task')
    op.drop_index('ix_venue_sub_task_venue', table_name='sync_venue_sub_task')
    op.create_index(op.f('ix_sync_venue_sub_task_status'), 'sync_venue_sub_task', ['status'], unique=False)
    op.create_index(op.f('ix_sync_venue_sub_task_sub_task_id'), 'sync_venue_sub_task', ['sub_task_id'], unique=False)
    op.create_index(op.f('ix_sync_venue_sub_task_task_id'), 'sync_venue_sub_task', ['task_id'], unique=False)
    op.create_index(op.f('ix_sync_venue_sub_task_venue_id'), 'sync_venue_sub_task', ['venue_id'], unique=False)
    op.drop_index('ix_sys_config_key', table_name='sys_config')
    op.drop_constraint('sys_config_config_key_key', 'sys_config', type_='unique')
    op.create_index(op.f('ix_sys_config_config_id'), 'sys_config', ['config_id'], unique=False)
    op.create_index(op.f('ix_sys_config_config_key'), 'sys_config', ['config_key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sys_config_config_key'), table_name='sys_config')
    op.drop_index(op.f('ix_sys_config_config_id'), table_name='sys_config')
    op.create_unique_constraint('sys_config_config_key_key', 'sys_config', ['config_key'])
    op.create_index('ix_sys_config_key', 'sys_config', ['config_key'], unique=False)
    op.drop_index(op.f('ix_sync_venue_sub_task_venue_id'), table_name='sync_venue_sub_task')
    op.drop_index(op.f('ix_sync_venue_sub_task_task_id'), table_name='sync_venue_sub_task')
    op.drop_index(op.f('ix_sync_venue_sub_task_sub_task_id'), table_name='sync_venue_sub_task')
    op.drop_index(op.f('ix_sync_venue_sub_task_status'), table_name='sync_venue_sub_task')
    op.create_index('ix_venue_sub_task_venue', 'sync_venue_sub_task', ['venue_id'], unique=False)
    op.create_index('ix_venue_sub_task_task', 'sync_venue_sub_task', ['task_id'], unique=False)
    op.create_index('ix_venue_sub_task_status', 'sync_venue_sub_task', ['status'], unique=False)
    op.alter_column('sync_venue_sub_task', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('sync_venue_sub_task', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('sync_venue_sub_task', 'updated_authors',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('sync_venue_sub_task', 'new_authors',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('sync_venue_sub_task', 'authors_fetched',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('sync_venue_sub_task', 'works_fetched',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.create_foreign_key('sync_collect_task_strategy_id_fkey', 'sync_collect_task', 'sync_collect_strategy', ['strategy_id'], ['strategy_id'])
    op.drop_index(op.f('ix_sync_collect_task_task_id'), table_name='sync_collect_task')
    op.drop_index(op.f('ix_sync_collect_task_task_code'), table_name='sync_collect_task')
    op.drop_index(op.f('ix_sync_collect_task_status'), table_name='sync_collect_task')
    op.create_unique_constraint('sync_collect_task_task_code_key', 'sync_collect_task', ['task_code'])
    op.create_index('ix_collect_task_strategy', 'sync_collect_task', ['strategy_id'], unique=False)
    op.create_index('ix_collect_task_status', 'sync_collect_task', ['status'], unique=False)
    op.create_index('ix_collect_task_code', 'sync_collect_task', ['task_code'], unique=False)
    op.alter_column('sync_collect_task', 'error_details',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('sync_collect_task', 'collect_mode',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'full'::character varying"))
    op.drop_index(op.f('ix_sync_collect_strategy_strategy_id'), table_name='sync_collect_strategy')
    op.drop_index(op.f('ix_sync_collect_strategy_strategy_code'), table_name='sync_collect_strategy')
    op.create_unique_constraint('sync_collect_strategy_strategy_code_key', 'sync_collect_strategy', ['strategy_code'])
    op.create_index('ix_collect_strategy_type', 'sync_collect_strategy', ['strategy_type'], unique=False)
    op.create_index('ix_collect_strategy_code', 'sync_collect_strategy', ['strategy_code'], unique=False)
    op.drop_index(op.f('ix_sync_collect_scope_scope_id'), table_name='sync_collect_scope')
    op.drop_index(op.f('ix_sync_collect_scope_scope_code'), table_name='sync_collect_scope')
    op.create_unique_constraint('sync_collect_scope_scope_code_key', 'sync_collect_scope', ['scope_code'])
    op.create_index('ix_collect_scope_type', 'sync_collect_scope', ['scope_type'], unique=False)
    op.create_index('ix_collect_scope_code', 'sync_collect_scope', ['scope_code'], unique=False)
    op.drop_index(op.f('ix_sync_batch_batch_id'), table_name='sync_batch')
    op.drop_index(op.f('ix_sync_batch_batch_code'), table_name='sync_batch')
    op.create_unique_constraint('sync_batch_batch_code_key', 'sync_batch', ['batch_code'])
    op.create_index('ix_sync_batch_code', 'sync_batch', ['batch_code'], unique=False)
    op.drop_column('sync_batch', 'updated_at')
    op.drop_column('sync_batch', 'created_at')
    op.drop_index(op.f('ix_std_school_alias_std_school_id'), table_name='std_school_alias')
    op.drop_index(op.f('ix_std_school_alias_alias_name'), table_name='std_school_alias')
    op.drop_index(op.f('ix_std_school_alias_alias_id'), table_name='std_school_alias')
    op.create_index('ix_school_alias_std', 'std_school_alias', ['std_school_id'], unique=False)
    op.alter_column('std_school_alias', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('std_school_alias', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'std_school', type_='foreignkey')
    op.drop_index(op.f('ix_std_school_std_school_id'), table_name='std_school')
    op.drop_index(op.f('ix_std_school_school_id'), table_name='std_school')
    op.drop_index(op.f('ix_std_school_ror'), table_name='std_school')
    op.drop_index(op.f('ix_std_school_openalex_institution_id'), table_name='std_school')
    op.drop_index(op.f('ix_std_school_name_normalized'), table_name='std_school')
    op.drop_index(op.f('ix_std_school_confirm_status'), table_name='std_school')
    op.create_unique_constraint('std_school_openalex_institution_id_key', 'std_school', ['openalex_institution_id'])
    op.create_index('ix_std_school_status', 'std_school', ['confirm_status'], unique=False)
    op.create_index('ix_std_school_school', 'std_school', ['school_id'], unique=False)
    op.create_index('ix_std_school_openalex', 'std_school', ['openalex_institution_id'], unique=False)
    op.create_index('ix_std_school_name', 'std_school', ['name_normalized'], unique=False)
    op.alter_column('std_school', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('std_school', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'std_author', type_='foreignkey')
    op.drop_index(op.f('ix_std_author_std_school_id'), table_name='std_author')
    op.drop_index(op.f('ix_std_author_std_author_id'), table_name='std_author')
    op.drop_index(op.f('ix_std_author_openalex_author_id'), table_name='std_author')
    op.drop_index(op.f('ix_std_author_name_normalized'), table_name='std_author')
    op.drop_index(op.f('ix_std_author_confirm_status'), table_name='std_author')
    op.create_unique_constraint('std_author_openalex_author_id_key', 'std_author', ['openalex_author_id'])
    op.create_index('ix_std_author_status', 'std_author', ['confirm_status'], unique=False)
    op.create_index('ix_std_author_school', 'std_author', ['std_school_id'], unique=False)
    op.create_index('ix_std_author_openalex', 'std_author', ['openalex_author_id'], unique=False)
    op.create_index('ix_std_author_name', 'std_author', ['name_normalized'], unique=False)
    op.alter_column('std_author', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('std_author', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('std_author', 'confidence_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text("'0.8'::double precision"))
    op.alter_column('std_author', 'i10_index',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('std_author', 'h_index',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('std_author', 'cited_by_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('std_author', 'works_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.create_index('ix_stats_research_topic_count', 'stats_research_topic', [sa.text('talent_count DESC')], unique=False)
    op.alter_column('stats_research_topic', 'talent_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('ix_stat_school_snapshot_stat_version'), table_name='stat_school_snapshot')
    op.drop_index(op.f('ix_stat_school_snapshot_snapshot_id'), table_name='stat_school_snapshot')
    op.create_index('ix_stat_school_snapshot_version', 'stat_school_snapshot', ['stat_version'], unique=False)
    op.drop_index(op.f('ix_stat_overview_snapshot_stat_version'), table_name='stat_overview_snapshot')
    op.drop_index(op.f('ix_stat_overview_snapshot_snapshot_id'), table_name='stat_overview_snapshot')
    op.create_index('ix_stat_overview_version', 'stat_overview_snapshot', ['stat_version'], unique=False)
    op.drop_index(op.f('ix_search_talent_document_talent_id'), table_name='search_talent_document')
    op.drop_index(op.f('ix_search_talent_document_school_id'), table_name='search_talent_document')
    op.drop_index(op.f('ix_search_talent_document_role_type'), table_name='search_talent_document')
    op.drop_index(op.f('ix_search_talent_document_is_active'), table_name='search_talent_document')
    op.drop_index(op.f('ix_search_talent_document_document_id'), table_name='search_talent_document')
    op.drop_index(op.f('ix_search_talent_document_country_code'), table_name='search_talent_document')
    op.create_unique_constraint('search_talent_document_talent_id_key', 'search_talent_document', ['talent_id'])
    op.create_index('ix_search_text', 'search_talent_document', [sa.text("to_tsvector('simple'::regconfig, search_text)")], unique=False, postgresql_using='gin')
    op.create_index('ix_search_talent_id', 'search_talent_document', ['talent_id'], unique=False)
    op.create_index('ix_search_talent_document_vector', 'search_talent_document', ['search_vector'], unique=False, postgresql_using='gin')
    op.create_index('ix_search_talent_document_name_trgm', 'search_talent_document', ['name'], unique=False, postgresql_using='gin')
    op.create_index('ix_search_school_id', 'search_talent_document', ['school_id'], unique=False)
    op.create_index('ix_search_role_type', 'search_talent_document', ['role_type'], unique=False)
    op.create_index('ix_search_country_code', 'search_talent_document', ['country_code'], unique=False)
    op.create_index('ix_search_active', 'search_talent_document', ['is_active'], unique=False)
    op.alter_column('search_talent_document', 'topic_tags',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.ARRAY(sa.VARCHAR()),
               existing_nullable=True)
    op.drop_index(op.f('ix_rel_author_tech_belong_tech_domain_id'), table_name='rel_author_tech_belong')
    op.drop_index(op.f('ix_rel_author_tech_belong_std_author_id'), table_name='rel_author_tech_belong')
    op.drop_index(op.f('ix_rel_author_tech_belong_openalex_author_id'), table_name='rel_author_tech_belong')
    op.drop_index(op.f('ix_rel_author_tech_belong_belong_id'), table_name='rel_author_tech_belong')
    op.create_index('ix_rel_author_tech_belong_source_venue_id', 'rel_author_tech_belong', ['source_venue_id'], unique=False)
    op.create_index('ix_rel_author_tech_belong_source_task_id', 'rel_author_tech_belong', ['source_task_id'], unique=False)
    op.create_index('ix_author_tech_venue', 'rel_author_tech_belong', ['source_venue_id'], unique=False)
    op.create_index('ix_author_tech_domain', 'rel_author_tech_belong', ['tech_domain_id'], unique=False)
    op.create_index('ix_author_tech_author', 'rel_author_tech_belong', ['openalex_author_id'], unique=False)
    op.alter_column('rel_author_tech_belong', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('rel_author_tech_belong', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('rel_author_tech_belong', 'work_count_in_venue',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.drop_index(op.f('ix_raw_work_source_id'), table_name='raw_work')
    op.drop_index(op.f('ix_raw_work_raw_work_id'), table_name='raw_work')
    op.drop_index(op.f('ix_raw_work_publication_year'), table_name='raw_work')
    op.drop_index(op.f('ix_raw_work_processed_status'), table_name='raw_work')
    op.drop_index(op.f('ix_raw_work_openalex_work_id'), table_name='raw_work')
    op.create_unique_constraint('raw_work_openalex_work_id_key', 'raw_work', ['openalex_work_id'])
    op.create_index('ix_raw_work_year', 'raw_work', ['publication_year'], unique=False)
    op.create_index('ix_raw_work_title_trgm', 'raw_work', ['title'], unique=False, postgresql_using='gin', postgresql_where='(title IS NOT NULL)')
    op.create_index('ix_raw_work_sub_task_id', 'raw_work', ['sub_task_id'], unique=False)
    op.create_index('ix_raw_work_status', 'raw_work', ['processed_status'], unique=False)
    op.create_index('ix_raw_work_source_year', 'raw_work', ['source_id', 'publication_year'], unique=False)
    op.create_index('ix_raw_work_source', 'raw_work', ['source_id'], unique=False)
    op.create_index('ix_raw_work_openalex', 'raw_work', ['openalex_work_id'], unique=False)
    op.create_index('ix_raw_work_fetch_task_id', 'raw_work', ['fetch_task_id'], unique=False)
    op.alter_column('raw_work', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('raw_work', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('raw_work', 'processed_status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('raw_work', 'author_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.drop_index(op.f('ix_raw_institution_std_school_id'), table_name='raw_institution')
    op.drop_index(op.f('ix_raw_institution_raw_institution_id'), table_name='raw_institution')
    op.drop_index(op.f('ix_raw_institution_processed_status'), table_name='raw_institution')
    op.drop_index(op.f('ix_raw_institution_openalex_institution_id'), table_name='raw_institution')
    op.drop_index(op.f('ix_raw_institution_display_name'), table_name='raw_institution')
    op.drop_index(op.f('ix_raw_institution_country_code'), table_name='raw_institution')
    op.create_unique_constraint('raw_institution_openalex_institution_id_key', 'raw_institution', ['openalex_institution_id'])
    op.create_index('ix_raw_inst_std', 'raw_institution', ['std_school_id'], unique=False)
    op.create_index('ix_raw_inst_status_task', 'raw_institution', ['processed_status', 'fetch_task_id'], unique=False)
    op.create_index('ix_raw_inst_status', 'raw_institution', ['processed_status'], unique=False)
    op.create_index('ix_raw_inst_openalex', 'raw_institution', ['openalex_institution_id'], unique=False)
    op.create_index('ix_raw_inst_name', 'raw_institution', ['display_name'], unique=False)
    op.create_index('ix_raw_inst_country', 'raw_institution', ['country_code'], unique=False)
    op.alter_column('raw_institution', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('raw_institution', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('raw_institution', 'processed_status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.drop_index(op.f('ix_raw_author_std_author_id'), table_name='raw_author')
    op.drop_index(op.f('ix_raw_author_raw_author_id'), table_name='raw_author')
    op.drop_index(op.f('ix_raw_author_processed_status'), table_name='raw_author')
    op.drop_index(op.f('ix_raw_author_openalex_author_id'), table_name='raw_author')
    op.drop_index(op.f('ix_raw_author_last_known_institution_id'), table_name='raw_author')
    op.drop_index(op.f('ix_raw_author_display_name'), table_name='raw_author')
    op.create_unique_constraint('raw_author_openalex_author_id_key', 'raw_author', ['openalex_author_id'])
    op.create_index('ix_raw_author_std', 'raw_author', ['std_author_id'], unique=False)
    op.create_index('ix_raw_author_status_task', 'raw_author', ['processed_status', 'fetch_task_id'], unique=False)
    op.create_index('ix_raw_author_status', 'raw_author', ['processed_status'], unique=False)
    op.create_index('ix_raw_author_openalex', 'raw_author', ['openalex_author_id'], unique=False)
    op.create_index('ix_raw_author_name', 'raw_author', ['display_name'], unique=False)
    op.create_index('ix_raw_author_inst', 'raw_author', ['last_known_institution_id'], unique=False)
    op.create_index('ix_raw_author_fetch_task_id', 'raw_author', ['fetch_task_id'], unique=False)
    op.alter_column('raw_author', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('raw_author', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('raw_author', 'processed_status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('raw_author', 'i10_index',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('raw_author', 'h_index',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('raw_author', 'cited_by_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('raw_author', 'works_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.drop_index(op.f('ix_os_talent_pool_pool_id'), table_name='os_talent_pool')
    op.drop_index(op.f('ix_os_talent_pool_owner_user_id'), table_name='os_talent_pool')
    op.create_index('ix_os_talent_pool_owner', 'os_talent_pool', ['owner_user_id'], unique=False)
    op.drop_constraint(None, 'os_repository', type_='unique')
    op.drop_index(op.f('ix_os_repository_repo_id'), table_name='os_repository')
    op.drop_index(op.f('ix_os_repository_github_repo_id'), table_name='os_repository')
    op.drop_index(op.f('ix_os_repository_developer_id'), table_name='os_repository')
    op.create_index('ix_os_repository_stars', 'os_repository', [sa.text('stars_count DESC')], unique=False)
    op.create_index('ix_os_repository_github_id', 'os_repository', ['github_repo_id'], unique=False)
    op.create_index('ix_os_repository_full_name', 'os_repository', ['full_name'], unique=True)
    op.create_index('ix_os_repository_dev_id', 'os_repository', ['developer_id'], unique=False)
    op.drop_index(op.f('ix_os_repo_mapping_repo_full_name'), table_name='os_repo_mapping')
    op.drop_index(op.f('ix_os_repo_mapping_mapping_id'), table_name='os_repo_mapping')
    op.create_index('ix_os_repo_mapping_repo', 'os_repo_mapping', ['repo_full_name'], unique=False)
    op.drop_index(op.f('ix_os_repo_config_repo_config_id'), table_name='os_repo_config')
    op.create_index('ix_os_repo_config_tech_element', 'os_repo_config', ['tech_element'], unique=False, postgresql_using='gin')
    op.create_index('ix_os_repo_config_collect', 'os_repo_config', ['is_active', 'collect_enabled'], unique=False)
    op.alter_column('os_repo_config', 'tech_element',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.drop_index(op.f('ix_os_raw_developer_raw_id'), table_name='os_raw_developer')
    op.drop_index(op.f('ix_os_raw_developer_github_login'), table_name='os_raw_developer')
    op.create_index('ix_os_raw_developer_login', 'os_raw_developer', ['github_login'], unique=False)
    op.drop_index(op.f('ix_os_pool_member_pool_member_id'), table_name='os_pool_member')
    op.create_index('ix_os_pool_member_pool_dev', 'os_pool_member', ['pool_id', 'developer_id'], unique=True)
    op.drop_index(op.f('ix_os_language_skill_skill_id'), table_name='os_language_skill')
    op.drop_index(op.f('ix_os_language_skill_developer_id'), table_name='os_language_skill')
    op.create_index('ix_os_language_skill_dev_lang', 'os_language_skill', ['developer_id', 'language'], unique=True)
    op.create_index('ix_os_language_skill_dev_id', 'os_language_skill', ['developer_id'], unique=False)
    op.drop_index(op.f('ix_os_favourite_favourite_id'), table_name='os_favourite')
    op.create_index('ix_os_favourite_user_dev', 'os_favourite', ['user_id', 'developer_id'], unique=True)
    op.drop_index(op.f('ix_os_embedding_source_text_hash'), table_name='os_embedding')
    op.drop_index(op.f('ix_os_embedding_embedding_id'), table_name='os_embedding')
    op.create_index('ix_os_embedding_vector', 'os_embedding', ['embedding'], unique=False, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.create_index('ix_os_embedding_hash', 'os_embedding', ['source_text_hash'], unique=False)
    op.create_index('ix_os_embedding_dev_type', 'os_embedding', ['developer_id', 'vector_type'], unique=True)
    op.drop_index(op.f('ix_os_developer_github_id'), table_name='os_developer')
    op.drop_index(op.f('ix_os_developer_developer_id'), table_name='os_developer')
    op.create_index('ix_os_developer_visible', 'os_developer', ['is_visible'], unique=False)
    op.create_index('ix_os_developer_tech_tags_gin', 'os_developer', ['tech_tags'], unique=False, postgresql_using='gin')
    op.create_index('ix_os_developer_stars_desc', 'os_developer', [sa.text('total_stars_received DESC')], unique=False)
    op.create_index('ix_os_developer_primary_languages_gin', 'os_developer', ['primary_languages'], unique=False, postgresql_using='gin')
    op.create_index('ix_os_developer_name_trgm', 'os_developer', ['name'], unique=False, postgresql_using='gin')
    op.create_index('ix_os_developer_location_trgm', 'os_developer', ['location'], unique=False, postgresql_using='gin')
    op.create_index('ix_os_developer_location', 'os_developer', ['location'], unique=False)
    op.create_index('ix_os_developer_github_login_trgm', 'os_developer', ['github_login'], unique=False, postgresql_using='gin')
    op.create_index('ix_os_developer_company_trgm', 'os_developer', ['company'], unique=False, postgresql_using='gin')
    op.create_index('ix_os_developer_company', 'os_developer', ['company'], unique=False)
    op.create_index('ix_os_developer_bio_trgm', 'os_developer', ['bio'], unique=False, postgresql_using='gin')
    op.drop_index(op.f('ix_os_contribution_developer_id'), table_name='os_contribution')
    op.drop_index(op.f('ix_os_contribution_contribution_id'), table_name='os_contribution')
    op.create_index('ix_os_contribution_dev_repo', 'os_contribution', ['developer_id', 'repo_id'], unique=True)
    op.create_index('ix_os_contribution_dev_id', 'os_contribution', ['developer_id'], unique=False)
    op.drop_index(op.f('ix_os_collect_task_task_id'), table_name='os_collect_task')
    op.create_index('ix_os_collect_task_created_at', 'os_collect_task', [sa.text('created_at DESC')], unique=False)
    op.create_unique_constraint('uq_lab_talent_dedup_hash', 'lab_talent', ['dedup_hash'])
    op.create_index('ix_lab_talent_advisor', 'lab_talent', ['advisor'], unique=False)
    op.create_unique_constraint('uq_lab_info_parent_lab', 'lab_info', ['parent_lab'])
    op.create_index('ix_lab_info_lab_info_id', 'lab_info', ['lab_info_id'], unique=False)
    op.drop_index(op.f('ix_jd_match_session_user_id'), table_name='jd_match_session')
    op.create_index('ix_jd_match_session_user', 'jd_match_session', ['user_id'], unique=False)
    op.create_index('ix_jd_match_session_created', 'jd_match_session', ['created_at'], unique=False)
    op.alter_column('jd_match_session', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('jd_match_session', 'completed_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='完成时间',
               existing_nullable=True)
    op.alter_column('jd_match_session', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='状态: pending/completed/failed',
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('jd_match_session', 'jd_features',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='LLM 解析出的 JD 特征',
               existing_nullable=True)
    op.alter_column('jd_match_session', 'jd_text',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='原始 JD 文本',
               existing_nullable=False)
    op.alter_column('jd_match_session', 'user_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='用户ID',
               existing_nullable=False)
    op.drop_index(op.f('ix_jd_match_result_talent_id'), table_name='jd_match_result')
    op.drop_index(op.f('ix_jd_match_result_session_id'), table_name='jd_match_result')
    op.create_index('ix_jd_match_result_talent', 'jd_match_result', ['talent_id'], unique=False)
    op.create_index('ix_jd_match_result_session', 'jd_match_result', ['session_id'], unique=False)
    op.create_index('ix_jd_match_result_score', 'jd_match_result', ['overall_score'], unique=False)
    op.alter_column('jd_match_result', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('jd_match_result', 'highlight_skills',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='匹配的技能列表',
               existing_nullable=True)
    op.alter_column('jd_match_result', 'match_reasons',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='匹配原因列表',
               existing_nullable=True)
    op.alter_column('jd_match_result', 'experience_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='经验匹配分数',
               existing_nullable=True)
    op.alter_column('jd_match_result', 'research_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='研究方向匹配分数',
               existing_nullable=True)
    op.alter_column('jd_match_result', 'skill_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='技能匹配分数',
               existing_nullable=True)
    op.alter_column('jd_match_result', 'overall_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='综合匹配分数 0-100',
               existing_nullable=True)
    op.alter_column('jd_match_result', 'talent_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='人才ID',
               existing_nullable=False)
    op.alter_column('jd_match_result', 'session_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='会话ID',
               existing_nullable=False)
    op.drop_index(op.f('ix_industry_talent_dedup_hash'), table_name='industry_talent')
    op.create_index('ix_industry_talent_dedup_hash', 'industry_talent', ['dedup_hash'], unique=False)
    op.create_unique_constraint('industry_talent_dedup_hash_key', 'industry_talent', ['dedup_hash'])
    op.drop_index(op.f('ix_iam_user_school_scope_user_id'), table_name='iam_user_school_scope')
    op.drop_index(op.f('ix_iam_user_school_scope_scope_id'), table_name='iam_user_school_scope')
    op.create_unique_constraint('uq_user_scope', 'iam_user_school_scope', ['user_id', 'scope_type', 'scope_value'])
    op.create_index('ix_iam_scope_user_id', 'iam_user_school_scope', ['user_id'], unique=False)
    op.create_index('ix_iam_scope_type_value', 'iam_user_school_scope', ['scope_type', 'scope_value'], unique=False)
    op.drop_index(op.f('ix_iam_user_account_username'), table_name='iam_user_account')
    op.drop_index(op.f('ix_iam_user_account_user_id'), table_name='iam_user_account')
    op.drop_index(op.f('ix_iam_user_account_employee_id'), table_name='iam_user_account')
    op.drop_index(op.f('ix_iam_user_account_email'), table_name='iam_user_account')
    op.create_index('ix_user_account_employee_id', 'iam_user_account', ['employee_id'], unique=True)
    op.create_index('ix_iam_user_username', 'iam_user_account', ['username'], unique=False)
    op.create_index('ix_iam_user_email', 'iam_user_account', ['email'], unique=False)
    op.create_index('ix_iam_user_account_created_at', 'iam_user_account', ['created_at'], unique=False)
    op.create_unique_constraint('iam_user_account_username_key', 'iam_user_account', ['username'])
    op.create_unique_constraint('iam_user_account_email_key', 'iam_user_account', ['email'])
    op.drop_index(op.f('ix_iam_talent_pool_member_talent_id'), table_name='iam_talent_pool_member')
    op.drop_index(op.f('ix_iam_talent_pool_member_pool_id'), table_name='iam_talent_pool_member')
    op.drop_index(op.f('ix_iam_talent_pool_member_member_id'), table_name='iam_talent_pool_member')
    op.create_index('ix_pool_member_talent', 'iam_talent_pool_member', ['talent_id'], unique=False)
    op.create_index('ix_pool_member_pool', 'iam_talent_pool_member', ['pool_id'], unique=False)
    op.drop_index(op.f('ix_iam_talent_pool_pool_id'), table_name='iam_talent_pool')
    op.drop_index(op.f('ix_iam_talent_pool_owner_user_id'), table_name='iam_talent_pool')
    op.create_index('ix_talent_pool_status', 'iam_talent_pool', ['pool_status'], unique=False)
    op.create_index('ix_talent_pool_owner', 'iam_talent_pool', ['owner_user_id'], unique=False)
    op.drop_index(op.f('ix_iam_favorite_talent_user_id'), table_name='iam_favorite_talent')
    op.drop_index(op.f('ix_iam_favorite_talent_talent_id'), table_name='iam_favorite_talent')
    op.drop_index(op.f('ix_iam_favorite_talent_favorite_id'), table_name='iam_favorite_talent')
    op.create_index('ix_iam_favorite_user_id', 'iam_favorite_talent', ['user_id'], unique=False)
    op.create_index('ix_iam_favorite_talent_id', 'iam_favorite_talent', ['talent_id'], unique=False)
    op.create_index('ix_iam_favorite_is_active', 'iam_favorite_talent', ['is_active'], unique=False)
    op.create_index('ix_favorite_user_active_created', 'iam_favorite_talent', ['user_id', 'is_active', sa.text('created_at DESC')], unique=False, postgresql_where='(is_active = true)')
    op.create_index('ix_genealogy_edge_confidence', 'genealogy_edge', ['confidence_score'], unique=False)
    op.drop_index(op.f('ix_data_version_version_id'), table_name='data_version')
    op.drop_index(op.f('ix_data_version_version_code'), table_name='data_version')
    op.drop_index(op.f('ix_data_version_is_active'), table_name='data_version')
    op.create_index('ix_data_version_code', 'data_version', ['version_code'], unique=False)
    op.create_index('ix_data_version_active', 'data_version', ['is_active'], unique=False)
    op.create_unique_constraint('data_version_version_code_key', 'data_version', ['version_code'])
    op.drop_index(op.f('ix_data_quality_summary_version_id'), table_name='data_quality_summary')
    op.drop_index(op.f('ix_data_quality_summary_summary_id'), table_name='data_quality_summary')
    op.drop_index(op.f('ix_data_quality_summary_summary_date'), table_name='data_quality_summary')
    op.create_index('ix_quality_summary_version', 'data_quality_summary', ['version_id'], unique=False)
    op.create_index('ix_quality_summary_date', 'data_quality_summary', ['summary_date'], unique=False)
    op.drop_index(op.f('ix_data_publish_record_version_id'), table_name='data_publish_record')
    op.drop_index(op.f('ix_data_publish_record_publish_id'), table_name='data_publish_record')
    op.create_index('ix_publish_record_version', 'data_publish_record', ['version_id'], unique=False)
    op.drop_index(op.f('ix_data_correction_record_target_type'), table_name='data_correction_record')
    op.drop_index(op.f('ix_data_correction_record_target_id'), table_name='data_correction_record')
    op.drop_index(op.f('ix_data_correction_record_correction_id'), table_name='data_correction_record')
    op.create_index('ix_correction_target', 'data_correction_record', ['target_type', 'target_id'], unique=False)
    op.create_index('ix_correction_status', 'data_correction_record', ['status'], unique=False)
    op.drop_constraint(None, 'core_work_author', type_='foreignkey')
    op.drop_index(op.f('ix_core_work_author_work_author_id'), table_name='core_work_author')
    op.create_index('ix_core_work_author_id', 'core_work_author', ['work_author_id'], unique=False)
    op.alter_column('core_work_author', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('core_work_author', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_index(op.f('ix_core_tech_domain_tech_domain_id'), table_name='core_tech_domain')
    op.create_index('ix_tech_element_enabled', 'core_tech_domain', ['is_enabled'], unique=False)
    op.create_index('ix_tech_element_code', 'core_tech_domain', ['domain_code'], unique=False)
    op.drop_index(op.f('ix_core_tech_direction_tech_domain_id'), table_name='core_tech_direction')
    op.drop_index(op.f('ix_core_tech_direction_tech_direction_id'), table_name='core_tech_direction')
    op.create_index('ix_tech_direction_enabled', 'core_tech_direction', ['is_enabled'], unique=False)
    op.create_index('ix_tech_direction_domain', 'core_tech_direction', ['tech_domain_id'], unique=False)
    op.create_index('ix_tech_direction_code', 'core_tech_direction', ['direction_code'], unique=False)
    op.drop_index(op.f('ix_core_talent_tech_tag_tech_domain_id'), table_name='core_talent_tech_tag')
    op.drop_index(op.f('ix_core_talent_tech_tag_tech_direction_id'), table_name='core_talent_tech_tag')
    op.drop_index(op.f('ix_core_talent_tech_tag_talent_id'), table_name='core_talent_tech_tag')
    op.drop_index(op.f('ix_core_talent_tech_tag_tag_id'), table_name='core_talent_tech_tag')
    op.create_index('ix_talent_tech_tag_talent', 'core_talent_tech_tag', ['talent_id'], unique=False)
    op.create_index('ix_talent_tech_tag_enabled', 'core_talent_tech_tag', ['is_enabled'], unique=False)
    op.create_index('ix_talent_tech_tag_domain', 'core_talent_tech_tag', ['tech_domain_id'], unique=False)
    op.create_index('ix_talent_tech_tag_direction', 'core_talent_tech_tag', ['tech_direction_id'], unique=False)
    op.create_index('ix_talent_tech_enabled_domain', 'core_talent_tech_tag', ['tech_domain_id'], unique=False, postgresql_where='(is_enabled = true)')
    op.create_index('ix_talent_tech_enabled_direction', 'core_talent_tech_tag', ['is_enabled', 'tech_direction_id', 'talent_id'], unique=False, postgresql_where='(is_enabled = true)')
    op.drop_index(op.f('ix_core_talent_embedding_vector_type'), table_name='core_talent_embedding')
    op.drop_index(op.f('ix_core_talent_embedding_talent_id'), table_name='core_talent_embedding')
    op.create_index('ix_talent_embedding_model', 'core_talent_embedding', ['model_name'], unique=False)
    op.create_index('ix_embedding_vector_type', 'core_talent_embedding', ['vector_type'], unique=False)
    op.create_index('ix_embedding_research', 'core_talent_embedding', ['embedding'], unique=False, postgresql_with={'lists': '100'}, postgresql_using='ivfflat', postgresql_where="((vector_type)::text = 'research'::text)")
    op.create_index('ix_embedding_papers', 'core_talent_embedding', ['embedding'], unique=False, postgresql_with={'lists': '100'}, postgresql_using='ivfflat', postgresql_where="((vector_type)::text = 'papers'::text)")
    op.alter_column('core_talent_embedding', 'source_text_hash',
               existing_type=sa.VARCHAR(length=64),
               comment=None,
               existing_comment='源文本哈希，用于判断是否需要更新',
               existing_nullable=False)
    op.alter_column('core_talent_embedding', 'model_name',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='嵌入模型名称',
               existing_nullable=False)
    op.alter_column('core_talent_embedding', 'embedding',
               existing_type=postgresql.JSONB(),
               comment=None,
               existing_comment='向量嵌入 (JSON或pgvector)',
               existing_nullable=False)
    op.alter_column('core_talent_embedding', 'vector_type',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='向量类型: research(研究方向) / papers(论文标题)',
               existing_nullable=False,
               existing_server_default=sa.text("'research'::character varying"))
    op.alter_column('core_talent_embedding', 'talent_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='关联人才ID',
               existing_nullable=False)
    op.drop_index(op.f('ix_core_talent_talent_id'), table_name='core_talent')
    op.drop_index(op.f('ix_core_talent_std_author_id'), table_name='core_talent')
    op.drop_index(op.f('ix_core_talent_education_school_id'), table_name='core_talent')
    op.drop_index(op.f('ix_core_talent_company_school_id'), table_name='core_talent')
    op.drop_index(op.f('ix_core_talent_source_record_id'), table_name='core_talent')
    op.create_index('ix_core_talent_source_record_id', 'core_talent', ['source_record_id'], unique=False)
    op.create_index('ix_talent_education_school', 'core_talent', ['education_school_id'], unique=False)
    op.create_index('ix_talent_company_school', 'core_talent', ['company_school_id'], unique=False)
    op.create_index('ix_core_talent_works_count', 'core_talent', ['works_count'], unique=False)
    op.create_index('ix_core_talent_visible_school_role', 'core_talent', ['is_visible', 'school_id', 'role_type'], unique=False)
    op.create_index('ix_core_talent_visible_cited_desc', 'core_talent', ['is_visible', sa.text('cited_by_count DESC')], unique=False)
    op.create_index('ix_core_talent_std_author', 'core_talent', ['std_author_id'], unique=False)
    op.create_index('ix_core_talent_source_record_id_unique', 'core_talent', ['source_record_id'], unique=True)
    op.create_index('ix_core_talent_school_role', 'core_talent', ['school_id', 'role_type', 'is_visible'], unique=False)
    op.create_index('ix_core_talent_openalex_topics_trgm', 'core_talent', [sa.text('(openalex_topics::text)')], unique=False, postgresql_using='gin', postgresql_where='(openalex_topics IS NOT NULL)')
    op.create_index('ix_core_talent_openalex_topics_gin', 'core_talent', [sa.text('(openalex_topics::jsonb)')], unique=False, postgresql_using='gin', postgresql_where='(openalex_topics IS NOT NULL)')
    op.create_index('ix_core_talent_h_index', 'core_talent', ['h_index'], unique=False)
    op.create_index('ix_core_talent_cited_by_count', 'core_talent', ['cited_by_count'], unique=False)
    op.alter_column('core_talent', 'topic_tags',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_index(op.f('ix_core_selected_work_work_id'), table_name='core_selected_work')
    op.drop_index(op.f('ix_core_school_alias_alias_id'), table_name='core_school_alias')
    op.drop_index(op.f('ix_core_school_school_id'), table_name='core_school')
    op.drop_index(op.f('ix_core_school_is_top_school'), table_name='core_school')
    op.drop_index(op.f('ix_core_school_source_record_id'), table_name='core_school')
    op.create_index('ix_core_school_source_record_id', 'core_school', ['source_record_id'], unique=False)
    op.create_index('ix_core_school_status_visible', 'core_school', ['status', 'is_visible'], unique=False)
    op.create_index('ix_core_school_source_record_id_unique', 'core_school', ['source_record_id'], unique=True)
    op.create_index('ix_core_school_is_top', 'core_school', ['is_top_school'], unique=False)
    op.alter_column('core_school', 'country_code',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.drop_index(op.f('ix_core_role_profile_profile_id'), table_name='core_role_profile')
    op.create_index('ix_core_role_profile_talent_id', 'core_role_profile', ['talent_id'], unique=False)
    op.drop_constraint(None, 'core_collaboration', type_='foreignkey')
    op.drop_constraint(None, 'core_collaboration', type_='foreignkey')
    op.drop_index(op.f('ix_core_collaboration_collaboration_id'), table_name='core_collaboration')
    op.create_index('ix_core_collaboration_id', 'core_collaboration', ['collaboration_id'], unique=False)
    op.alter_column('core_collaboration', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('core_collaboration', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_index(op.f('ix_config_venue_tech_binding_venue_id'), table_name='config_venue_tech_binding')
    op.drop_index(op.f('ix_config_venue_tech_binding_tech_domain_id'), table_name='config_venue_tech_binding')
    op.drop_index(op.f('ix_config_venue_tech_binding_binding_id'), table_name='config_venue_tech_binding')
    op.create_index('ix_venue_binding_venue', 'config_venue_tech_binding', ['venue_id'], unique=False)
    op.create_index('ix_venue_binding_tech', 'config_venue_tech_binding', ['tech_domain_id'], unique=False)
    op.create_index('ix_venue_binding_status', 'config_venue_tech_binding', ['collect_status'], unique=False)
    op.alter_column('config_venue_tech_binding', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('config_venue_tech_binding', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('config_venue_tech_binding', 'work_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('config_venue_tech_binding', 'author_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('config_venue_tech_binding', 'priority',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.drop_index(op.f('ix_config_venue_venue_id'), table_name='config_venue')
    op.drop_index(op.f('ix_config_venue_venue_code'), table_name='config_venue')
    op.drop_index(op.f('ix_config_venue_openalex_source_id'), table_name='config_venue')
    op.create_index('ix_config_venue_type', 'config_venue', ['venue_type'], unique=False)
    op.create_index('ix_config_venue_openalex_id', 'config_venue', ['openalex_source_id'], unique=False)
    op.create_index('ix_config_venue_name', 'config_venue', ['venue_name'], unique=False)
    op.create_index('ix_config_venue_code', 'config_venue', ['venue_code'], unique=False)
    op.create_unique_constraint('config_venue_venue_code_key', 'config_venue', ['venue_code'])
    op.create_unique_constraint('config_venue_openalex_source_id_key', 'config_venue', ['openalex_source_id'])
    op.alter_column('config_venue', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('config_venue', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('config_venue', 'cited_by_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('config_venue', 'works_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('config_venue', 'h_index',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.drop_index(op.f('ix_audit_operation_log_user_id'), table_name='audit_operation_log')
    op.drop_index(op.f('ix_audit_operation_log_resource_type'), table_name='audit_operation_log')
    op.drop_index(op.f('ix_audit_operation_log_request_id'), table_name='audit_operation_log')
    op.drop_index(op.f('ix_audit_operation_log_log_id'), table_name='audit_operation_log')
    op.drop_index(op.f('ix_audit_operation_log_event_type'), table_name='audit_operation_log')
    op.drop_index(op.f('ix_audit_operation_log_event_time'), table_name='audit_operation_log')
    op.create_index('ix_audit_user_event', 'audit_operation_log', ['user_id', 'event_time'], unique=False)
    op.create_index('ix_audit_resource', 'audit_operation_log', ['resource_type', 'resource_id'], unique=False)
    op.create_index('ix_audit_request_id', 'audit_operation_log', ['request_id'], unique=False)
    op.create_index('ix_audit_event_type', 'audit_operation_log', ['event_type', 'event_time'], unique=False)
    op.create_index('ix_audit_event_time', 'audit_operation_log', ['event_time'], unique=False)
    # ### end Alembic commands ###
