/**
 * Industry domain display constants — status labels/colors, score tiers.
 * Labels mirror backend app/domains/industry/constants/status_config.py.
 */

import type { CSSProperties } from 'react'

// Candidate recruiting status (position-talent link)
export const CANDIDATE_STATUS_LABELS: Record<string, string> = {
  new: '新候选人',
  contacted: '已触达',
  interviewed: '面试中',
  rejected: '已淘汰',
  hired: '已入职',
}

// Ant Design Tag preset colors: new 蓝 / contacted 橙 / interviewed 紫 / rejected 灰 / hired 绿
export const CANDIDATE_STATUS_COLORS: Record<string, string> = {
  new: 'blue',
  contacted: 'orange',
  interviewed: 'purple',
  rejected: 'default',
  hired: 'green',
}

export const CANDIDATE_STATUS_OPTIONS = Object.entries(CANDIDATE_STATUS_LABELS).map(
  ([value, label]) => ({ value, label })
)

// Position lifecycle
export const POSITION_STATUS_LABELS: Record<string, string> = {
  open: '在招',
  closed: '已关闭',
  archived: '已归档',
}

export const POSITION_STATUS_COLORS: Record<string, string> = {
  open: 'green',
  closed: 'orange',
  archived: 'default',
}

export const SOURCE_PLATFORM_LABELS: Record<string, string> = {
  maimai: '脉脉',
  linkedin: 'LinkedIn',
}

export const SOURCE_PLATFORM_OPTIONS = [
  { value: 'maimai', label: '脉脉' },
  { value: 'linkedin', label: 'LinkedIn' },
]

export const INDUSTRY_SORT_OPTIONS = [
  { value: 'match_score_desc', label: '匹配分降序' },
  { value: 'match_score_asc', label: '匹配分升序' },
  { value: 'created_desc', label: '最近导入' },
  { value: 'name_asc', label: '姓名升序' },
]

export const MIN_SCORE_OPTIONS = [
  { value: 0, label: '不限分数' },
  { value: 60, label: '60 分以上' },
  { value: 70, label: '70 分以上' },
  { value: 80, label: '80 分以上' },
  { value: 90, label: '90 分以上' },
]

/** Match-score visual tiers: S 橙 / A+ 紫 / A 蓝 / B+ 绿 / C 灰 */
export function scoreColor(score: number | null | undefined): string {
  if (score === null || score === undefined) return '#94a3b8'
  if (score >= 100) return '#ea580c' // S — 橙
  if (score >= 95) return '#7c3aed'  // A+ — 紫
  if (score >= 90) return '#2563eb'  // A — 蓝
  if (score >= 80) return '#16a34a'  // B+ — 绿
  return '#94a3b8'                   // C — 灰
}

/** Soft background tint for each grade tier */
export function scoreBg(score: number | null | undefined): string {
  if (score === null || score === undefined) return '#f1f5f9'
  if (score >= 100) return '#f9f0ff'
  if (score >= 95) return '#e6f4ff'
  if (score >= 90) return '#f6ffed'
  if (score >= 80) return '#fff7e6'
  return '#f1f5f9'
}

export function formatScore(score: number | null | undefined): string {
  if (score === null || score === undefined) return '—'
  if (score >= 100) return 'S'
  if (score >= 95) return 'A+'
  if (score >= 90) return 'A'
  if (score >= 80) return 'B+'
  return 'C'
}

/**
 * Scalloped medal clip-path (12-petal rosette, like a classic award medal).
 * Generated by alternating outer/inner radius points around a circle.
 */
function medalClipPath(bumps = 12, outerR = 50, innerR = 41): string {
  const pts: string[] = []
  for (let i = 0; i < bumps * 2; i++) {
    const angle = (i * Math.PI) / bumps - Math.PI / 2 // start from top
    const r = i % 2 === 0 ? outerR : innerR
    const x = 50 + r * Math.cos(angle)
    const y = 50 + r * Math.sin(angle)
    pts.push(`${x.toFixed(2)}% ${y.toFixed(2)}%`)
  }
  return `polygon(${pts.join(', ')})`
}

// Pre-compute once — 12 petals gives a smooth rosette
const MEDAL_CLIP = medalClipPath()

/**
 * Premium medal-style grade badge generator.
 *
 * Design: scalloped rosette shape (like an award medal) with diagonal
 * gradient, drop-shadow glow, and white text. Shape is via clip-path
 * (12-petal rosette) so box-shadow won't work — uses filter:drop-shadow.
 *
 * @param size pixel size (width = height)
 * @returns CSSProperties for the badge container
 */
export function badgeStyle(
  score: number | null | undefined,
  size: number = 44
): CSSProperties {
  const fontSize = Math.round(size * 0.38)
  const glowSize = Math.max(4, Math.round(size * 0.12))

  const base: CSSProperties = {
    width: size,
    height: size,
    clipPath: MEDAL_CLIP,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    lineHeight: 1,
    flexShrink: 0,
    fontSize,
    fontWeight: 800,
    color: '#fff',
    textShadow: '0 1px 2px rgba(0,0,0,0.25)',
  }

  if (score === null || score === undefined) {
    return {
      ...base,
      background: 'linear-gradient(135deg, #e2e8f0, #cbd5e1)',
      color: '#64748b',
      textShadow: 'none',
    }
  }

  const tiers: { min: number; bg: string; glow: string }[] = [
    { min: 100, bg: 'linear-gradient(135deg, #fb923c, #ea580c)', glow: `drop-shadow(0 0 ${glowSize}px rgba(234,88,12,0.5))` },
    { min: 95, bg: 'linear-gradient(135deg, #a78bfa, #7c3aed)', glow: `drop-shadow(0 2px ${glowSize}px rgba(124,58,237,0.45))` },
    { min: 90, bg: 'linear-gradient(135deg, #60a5fa, #2563eb)', glow: `drop-shadow(0 2px ${glowSize}px rgba(37,99,235,0.45))` },
    { min: 80, bg: 'linear-gradient(135deg, #4ade80, #16a34a)', glow: `drop-shadow(0 2px ${glowSize}px rgba(22,163,74,0.45))` },
  ]

  for (const tier of tiers) {
    if (score >= tier.min) {
      return {
        ...base,
        background: tier.bg,
        filter: tier.glow,
      }
    }
  }

  return {
    ...base,
    background: 'linear-gradient(135deg, #cbd5e1, #94a3b8)',
    filter: `drop-shadow(0 1px 3px rgba(0,0,0,0.15))`,
  }
}

/**
 * Wrapper style for badge container — adds padding so the drop-shadow
 * glow isn't clipped by overflow:hidden parents. Apply to the parent
 * div wrapping the badge.
 */
export function badgeWrap(size: number = 44): CSSProperties {
  const pad = Math.round(size * 0.15)
  return { padding: pad, flexShrink: 0 }
}
