"""add unique constraints for source_record_id

Revision ID: 7850ff4764a7
Revises: 023
Create Date: 2026-04-07 18:33:21.804471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7850ff4764a7'
down_revision: Union[str, None] = '023'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_operation_log',
    sa.Column('log_id', sa.Integer(), nullable=False),
    sa.Column('event_time', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('user_ip', sa.String(length=50), nullable=True),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('event_subtype', sa.String(length=50), nullable=True),
    sa.Column('resource_type', sa.String(length=50), nullable=True),
    sa.Column('resource_id', sa.String(length=100), nullable=True),
    sa.Column('operation', sa.String(length=50), nullable=False),
    sa.Column('operation_detail', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('request_id', sa.String(length=100), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_index(op.f('ix_audit_operation_log_event_time'), 'audit_operation_log', ['event_time'], unique=False)
    op.create_index(op.f('ix_audit_operation_log_event_type'), 'audit_operation_log', ['event_type'], unique=False)
    op.create_index(op.f('ix_audit_operation_log_log_id'), 'audit_operation_log', ['log_id'], unique=False)
    op.create_index(op.f('ix_audit_operation_log_request_id'), 'audit_operation_log', ['request_id'], unique=False)
    op.create_index(op.f('ix_audit_operation_log_resource_type'), 'audit_operation_log', ['resource_type'], unique=False)
    op.create_index(op.f('ix_audit_operation_log_user_id'), 'audit_operation_log', ['user_id'], unique=False)
    op.create_table('config_venue',
    sa.Column('venue_id', sa.Integer(), nullable=False),
    sa.Column('venue_code', sa.String(length=50), nullable=False),
    sa.Column('venue_name', sa.String(length=255), nullable=False),
    sa.Column('venue_name_en', sa.String(length=255), nullable=True),
    sa.Column('openalex_source_id', sa.String(length=50), nullable=True),
    sa.Column('venue_type', sa.String(length=30), nullable=False),
    sa.Column('country_code', sa.String(length=10), nullable=True),
    sa.Column('publisher', sa.String(length=100), nullable=True),
    sa.Column('h_index', sa.Integer(), nullable=True),
    sa.Column('works_count', sa.Integer(), nullable=True),
    sa.Column('cited_by_count', sa.Integer(), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('last_collect_at', sa.DateTime(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('venue_id')
    )
    op.create_index(op.f('ix_config_venue_openalex_source_id'), 'config_venue', ['openalex_source_id'], unique=True)
    op.create_index(op.f('ix_config_venue_venue_code'), 'config_venue', ['venue_code'], unique=True)
    op.create_index(op.f('ix_config_venue_venue_id'), 'config_venue', ['venue_id'], unique=False)
    op.create_table('core_school',
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('school_name', sa.String(length=255), nullable=False),
    sa.Column('school_alias', sa.String(length=255), nullable=True),
    sa.Column('country_code', sa.String(length=10), nullable=False),
    sa.Column('country_name', sa.String(length=100), nullable=True),
    sa.Column('school_intro', sa.Text(), nullable=True),
    sa.Column('homepage_url', sa.String(length=500), nullable=True),
    sa.Column('professor_count', sa.Integer(), nullable=True),
    sa.Column('student_count', sa.Integer(), nullable=True),
    sa.Column('is_visible', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('is_top_school', sa.Boolean(), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=True),
    sa.Column('source_record_id', sa.String(length=100), nullable=True),
    sa.Column('last_sync_batch_id', sa.Integer(), nullable=True),
    sa.Column('department_name', sa.String(length=255), nullable=True),
    sa.Column('lab_name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('school_id')
    )
    op.create_index(op.f('ix_core_school_country_code'), 'core_school', ['country_code'], unique=False)
    op.create_index(op.f('ix_core_school_is_top_school'), 'core_school', ['is_top_school'], unique=False)
    op.create_index(op.f('ix_core_school_school_id'), 'core_school', ['school_id'], unique=False)
    op.create_index(op.f('ix_core_school_school_name'), 'core_school', ['school_name'], unique=False)
    op.create_index(op.f('ix_core_school_source_record_id'), 'core_school', ['source_record_id'], unique=False)
    op.create_index('ix_core_school_source_record_id_unique', 'core_school', ['source_record_id'], unique=True, postgresql_where=sa.text('source_record_id IS NOT NULL'))
    op.create_table('core_tech_element',
    sa.Column('tech_element_id', sa.Integer(), nullable=False),
    sa.Column('element_code', sa.String(length=50), nullable=False),
    sa.Column('element_name', sa.String(length=100), nullable=False),
    sa.Column('element_name_en', sa.String(length=100), nullable=True),
    sa.Column('element_desc', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('last_collect_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('tech_element_id'),
    sa.UniqueConstraint('element_code')
    )
    op.create_index(op.f('ix_core_tech_element_tech_element_id'), 'core_tech_element', ['tech_element_id'], unique=False)
    op.create_table('iam_user_account',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role_type', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=True),
    sa.Column('department', sa.String(length=255), nullable=True),
    sa.Column('default_view', sa.String(length=30), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('last_login_ip', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_iam_user_account_email'), 'iam_user_account', ['email'], unique=True)
    op.create_index(op.f('ix_iam_user_account_user_id'), 'iam_user_account', ['user_id'], unique=False)
    op.create_index(op.f('ix_iam_user_account_username'), 'iam_user_account', ['username'], unique=True)
    op.create_table('search_talent_document',
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('talent_id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('school_name', sa.String(length=255), nullable=True),
    sa.Column('country_code', sa.String(length=10), nullable=True),
    sa.Column('search_text', sa.Text(), nullable=False),
    sa.Column('role_type', sa.String(length=20), nullable=False),
    sa.Column('topic_tags', sa.JSON(), nullable=True),
    sa.Column('works_count', sa.Integer(), nullable=True),
    sa.Column('cited_by_count', sa.Integer(), nullable=True),
    sa.Column('h_index', sa.Integer(), nullable=True),
    sa.Column('latest_active_year', sa.Integer(), nullable=True),
    sa.Column('orcid', sa.String(length=50), nullable=True),
    sa.Column('batch_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('document_id')
    )
    op.create_index(op.f('ix_search_talent_document_country_code'), 'search_talent_document', ['country_code'], unique=False)
    op.create_index(op.f('ix_search_talent_document_document_id'), 'search_talent_document', ['document_id'], unique=False)
    op.create_index(op.f('ix_search_talent_document_is_active'), 'search_talent_document', ['is_active'], unique=False)
    op.create_index(op.f('ix_search_talent_document_role_type'), 'search_talent_document', ['role_type'], unique=False)
    op.create_index(op.f('ix_search_talent_document_school_id'), 'search_talent_document', ['school_id'], unique=False)
    op.create_index(op.f('ix_search_talent_document_talent_id'), 'search_talent_document', ['talent_id'], unique=True)
    op.create_table('stat_overview_snapshot',
    sa.Column('snapshot_id', sa.Integer(), nullable=False),
    sa.Column('stat_version', sa.String(length=50), nullable=False),
    sa.Column('generated_at', sa.String(length=50), nullable=False),
    sa.Column('school_count', sa.Integer(), nullable=True),
    sa.Column('professor_count', sa.Integer(), nullable=True),
    sa.Column('student_count', sa.Integer(), nullable=True),
    sa.Column('talent_count', sa.Integer(), nullable=True),
    sa.Column('country_count', sa.Integer(), nullable=True),
    sa.Column('tech_element_count', sa.Integer(), nullable=True),
    sa.Column('tech_direction_count', sa.Integer(), nullable=True),
    sa.Column('generated_by_batch_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('snapshot_id')
    )
    op.create_index(op.f('ix_stat_overview_snapshot_snapshot_id'), 'stat_overview_snapshot', ['snapshot_id'], unique=False)
    op.create_index(op.f('ix_stat_overview_snapshot_stat_version'), 'stat_overview_snapshot', ['stat_version'], unique=False)
    op.create_table('sync_batch',
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('batch_code', sa.String(length=50), nullable=False),
    sa.Column('batch_type', sa.String(length=20), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('total_records', sa.Integer(), nullable=True),
    sa.Column('success_records', sa.Integer(), nullable=True),
    sa.Column('failed_records', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_details', sa.JSON(), nullable=True),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('config_snapshot', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('batch_id')
    )
    op.create_index(op.f('ix_sync_batch_batch_code'), 'sync_batch', ['batch_code'], unique=True)
    op.create_index(op.f('ix_sync_batch_batch_id'), 'sync_batch', ['batch_id'], unique=False)
    op.create_index(op.f('ix_sync_batch_status'), 'sync_batch', ['status'], unique=False)
    op.create_table('config_venue_tech_binding',
    sa.Column('binding_id', sa.Integer(), nullable=False),
    sa.Column('venue_id', sa.Integer(), nullable=False),
    sa.Column('tech_element_id', sa.Integer(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('collect_status', sa.String(length=20), nullable=False),
    sa.Column('last_collect_at', sa.DateTime(), nullable=True),
    sa.Column('author_count', sa.Integer(), nullable=True),
    sa.Column('work_count', sa.Integer(), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tech_element_id'], ['core_tech_element.tech_element_id'], ),
    sa.ForeignKeyConstraint(['venue_id'], ['config_venue.venue_id'], ),
    sa.PrimaryKeyConstraint('binding_id'),
    sa.UniqueConstraint('venue_id', 'tech_element_id', name='uq_venue_tech_element')
    )
    op.create_index(op.f('ix_config_venue_tech_binding_binding_id'), 'config_venue_tech_binding', ['binding_id'], unique=False)
    op.create_index(op.f('ix_config_venue_tech_binding_tech_element_id'), 'config_venue_tech_binding', ['tech_element_id'], unique=False)
    op.create_index(op.f('ix_config_venue_tech_binding_venue_id'), 'config_venue_tech_binding', ['venue_id'], unique=False)
    op.create_table('core_school_alias',
    sa.Column('alias_id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('alias_name', sa.String(length=255), nullable=False),
    sa.Column('alias_type', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['core_school.school_id'], ),
    sa.PrimaryKeyConstraint('alias_id')
    )
    op.create_index(op.f('ix_core_school_alias_alias_id'), 'core_school_alias', ['alias_id'], unique=False)
    op.create_index(op.f('ix_core_school_alias_alias_name'), 'core_school_alias', ['alias_name'], unique=False)
    op.create_index(op.f('ix_core_school_alias_school_id'), 'core_school_alias', ['school_id'], unique=False)
    op.create_table('core_tech_direction',
    sa.Column('tech_direction_id', sa.Integer(), nullable=False),
    sa.Column('direction_code', sa.String(length=50), nullable=False),
    sa.Column('direction_name', sa.String(length=100), nullable=False),
    sa.Column('direction_name_en', sa.String(length=100), nullable=True),
    sa.Column('tech_element_id', sa.Integer(), nullable=False),
    sa.Column('direction_desc', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tech_element_id'], ['core_tech_element.tech_element_id'], ),
    sa.PrimaryKeyConstraint('tech_direction_id'),
    sa.UniqueConstraint('direction_code')
    )
    op.create_index(op.f('ix_core_tech_direction_tech_direction_id'), 'core_tech_direction', ['tech_direction_id'], unique=False)
    op.create_index(op.f('ix_core_tech_direction_tech_element_id'), 'core_tech_direction', ['tech_element_id'], unique=False)
    op.create_table('data_correction_record',
    sa.Column('correction_id', sa.Integer(), nullable=False),
    sa.Column('target_type', sa.String(length=30), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('field_name', sa.String(length=50), nullable=False),
    sa.Column('original_value', sa.Text(), nullable=True),
    sa.Column('corrected_value', sa.Text(), nullable=True),
    sa.Column('correction_type', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('corrected_by', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['corrected_by'], ['iam_user_account.user_id'], ),
    sa.PrimaryKeyConstraint('correction_id')
    )
    op.create_index(op.f('ix_data_correction_record_correction_id'), 'data_correction_record', ['correction_id'], unique=False)
    op.create_index(op.f('ix_data_correction_record_target_id'), 'data_correction_record', ['target_id'], unique=False)
    op.create_index(op.f('ix_data_correction_record_target_type'), 'data_correction_record', ['target_type'], unique=False)
    op.create_table('iam_talent_pool',
    sa.Column('pool_id', sa.Integer(), nullable=False),
    sa.Column('pool_name', sa.String(length=100), nullable=False),
    sa.Column('pool_type', sa.String(length=30), nullable=False),
    sa.Column('owner_user_id', sa.Integer(), nullable=False),
    sa.Column('scope_desc', sa.Text(), nullable=True),
    sa.Column('pool_status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['iam_user_account.user_id'], ),
    sa.PrimaryKeyConstraint('pool_id')
    )
    op.create_index(op.f('ix_iam_talent_pool_owner_user_id'), 'iam_talent_pool', ['owner_user_id'], unique=False)
    op.create_index(op.f('ix_iam_talent_pool_pool_id'), 'iam_talent_pool', ['pool_id'], unique=False)
    op.create_table('iam_user_school_scope',
    sa.Column('scope_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('scope_type', sa.String(length=20), nullable=False),
    sa.Column('scope_value', sa.String(length=100), nullable=True),
    sa.Column('granted_by', sa.Integer(), nullable=False),
    sa.Column('granted_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['iam_user_account.user_id'], ),
    sa.PrimaryKeyConstraint('scope_id')
    )
    op.create_index(op.f('ix_iam_user_school_scope_scope_id'), 'iam_user_school_scope', ['scope_id'], unique=False)
    op.create_index(op.f('ix_iam_user_school_scope_user_id'), 'iam_user_school_scope', ['user_id'], unique=False)
    op.create_table('stat_school_snapshot',
    sa.Column('snapshot_id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('stat_version', sa.String(length=50), nullable=False),
    sa.Column('generated_at', sa.String(length=50), nullable=False),
    sa.Column('professor_count', sa.Integer(), nullable=True),
    sa.Column('student_count', sa.Integer(), nullable=True),
    sa.Column('talent_count', sa.Integer(), nullable=True),
    sa.Column('graduate_count', sa.Integer(), nullable=True),
    sa.Column('unknown_count', sa.Integer(), nullable=True),
    sa.Column('generated_by_batch_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['school_id'], ['core_school.school_id'], ),
    sa.PrimaryKeyConstraint('snapshot_id')
    )
    op.create_index(op.f('ix_stat_school_snapshot_school_id'), 'stat_school_snapshot', ['school_id'], unique=False)
    op.create_index(op.f('ix_stat_school_snapshot_snapshot_id'), 'stat_school_snapshot', ['snapshot_id'], unique=False)
    op.create_index(op.f('ix_stat_school_snapshot_stat_version'), 'stat_school_snapshot', ['stat_version'], unique=False)
    op.create_table('sync_collect_scope',
    sa.Column('scope_id', sa.Integer(), nullable=False),
    sa.Column('scope_code', sa.String(length=50), nullable=False),
    sa.Column('scope_name', sa.String(length=100), nullable=False),
    sa.Column('scope_type', sa.String(length=30), nullable=False),
    sa.Column('scope_value', sa.JSON(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['iam_user_account.user_id'], ),
    sa.PrimaryKeyConstraint('scope_id')
    )
    op.create_index(op.f('ix_sync_collect_scope_scope_code'), 'sync_collect_scope', ['scope_code'], unique=True)
    op.create_index(op.f('ix_sync_collect_scope_scope_id'), 'sync_collect_scope', ['scope_id'], unique=False)
    op.create_table('sync_collect_strategy',
    sa.Column('strategy_id', sa.Integer(), nullable=False),
    sa.Column('strategy_code', sa.String(length=50), nullable=False),
    sa.Column('strategy_name', sa.String(length=100), nullable=False),
    sa.Column('strategy_type', sa.String(length=30), nullable=False),
    sa.Column('schedule_cron', sa.String(length=100), nullable=True),
    sa.Column('scope_ids', sa.JSON(), nullable=True),
    sa.Column('data_types', sa.JSON(), nullable=False),
    sa.Column('fetch_config', sa.JSON(), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.Column('last_run_status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['iam_user_account.user_id'], ),
    sa.PrimaryKeyConstraint('strategy_id')
    )
    op.create_index(op.f('ix_sync_collect_strategy_strategy_code'), 'sync_collect_strategy', ['strategy_code'], unique=True)
    op.create_index(op.f('ix_sync_collect_strategy_strategy_id'), 'sync_collect_strategy', ['strategy_id'], unique=False)
    op.create_table('sync_collect_task',
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('task_code', sa.String(length=50), nullable=False),
    sa.Column('strategy_id', sa.Integer(), nullable=True),
    sa.Column('task_type', sa.String(length=30), nullable=False),
    sa.Column('tech_element_id', sa.Integer(), nullable=True),
    sa.Column('collect_mode', sa.String(length=20), nullable=False),
    sa.Column('time_window_start', sa.DateTime(), nullable=True),
    sa.Column('time_window_end', sa.DateTime(), nullable=True),
    sa.Column('triggered_by', sa.Integer(), nullable=True),
    sa.Column('triggered_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('progress_percent', sa.Integer(), nullable=True),
    sa.Column('current_step', sa.String(length=100), nullable=True),
    sa.Column('total_records', sa.Integer(), nullable=True),
    sa.Column('processed_records', sa.Integer(), nullable=True),
    sa.Column('success_records', sa.Integer(), nullable=True),
    sa.Column('failed_records', sa.Integer(), nullable=True),
    sa.Column('skipped_records', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_details', sa.JSON(), nullable=True),
    sa.Column('result_summary', sa.JSON(), nullable=True),
    sa.Column('execution_logs', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tech_element_id'], ['core_tech_element.tech_element_id'], ),
    sa.ForeignKeyConstraint(['triggered_by'], ['iam_user_account.user_id'], ),
    sa.PrimaryKeyConstraint('task_id')
    )
    op.create_index(op.f('ix_sync_collect_task_status'), 'sync_collect_task', ['status'], unique=False)
    op.create_index(op.f('ix_sync_collect_task_task_code'), 'sync_collect_task', ['task_code'], unique=True)
    op.create_index(op.f('ix_sync_collect_task_task_id'), 'sync_collect_task', ['task_id'], unique=False)
    op.create_index(op.f('ix_sync_collect_task_tech_element_id'), 'sync_collect_task', ['tech_element_id'], unique=False)
    op.create_table('data_version',
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('version_code', sa.String(length=50), nullable=False),
    sa.Column('version_name', sa.String(length=100), nullable=False),
    sa.Column('version_type', sa.String(length=20), nullable=False),
    sa.Column('base_version_id', sa.Integer(), nullable=True),
    sa.Column('source_task_id', sa.Integer(), nullable=True),
    sa.Column('total_talents', sa.Integer(), nullable=True),
    sa.Column('total_schools', sa.Integer(), nullable=True),
    sa.Column('total_works', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('published_by', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['base_version_id'], ['data_version.version_id'], ),
    sa.ForeignKeyConstraint(['published_by'], ['iam_user_account.user_id'], ),
    sa.ForeignKeyConstraint(['source_task_id'], ['sync_collect_task.task_id'], ),
    sa.PrimaryKeyConstraint('version_id')
    )
    op.create_index(op.f('ix_data_version_is_active'), 'data_version', ['is_active'], unique=False)
    op.create_index(op.f('ix_data_version_version_code'), 'data_version', ['version_code'], unique=True)
    op.create_index(op.f('ix_data_version_version_id'), 'data_version', ['version_id'], unique=False)
    op.create_table('raw_author',
    sa.Column('raw_author_id', sa.Integer(), nullable=False),
    sa.Column('openalex_author_id', sa.String(length=50), nullable=False),
    sa.Column('raw_json', sa.Text(), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('orcid', sa.String(length=50), nullable=True),
    sa.Column('works_count', sa.Integer(), nullable=True),
    sa.Column('cited_by_count', sa.Integer(), nullable=True),
    sa.Column('h_index', sa.Integer(), nullable=True),
    sa.Column('i10_index', sa.Integer(), nullable=True),
    sa.Column('last_known_institution_id', sa.String(length=50), nullable=True),
    sa.Column('last_known_institution_name', sa.String(length=255), nullable=True),
    sa.Column('processed_status', sa.String(length=20), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('error_info', sa.Text(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.Column('fetch_task_id', sa.Integer(), nullable=True),
    sa.Column('std_author_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['fetch_task_id'], ['sync_collect_task.task_id'], ),
    sa.PrimaryKeyConstraint('raw_author_id')
    )
    op.create_index(op.f('ix_raw_author_display_name'), 'raw_author', ['display_name'], unique=False)
    op.create_index(op.f('ix_raw_author_last_known_institution_id'), 'raw_author', ['last_known_institution_id'], unique=False)
    op.create_index(op.f('ix_raw_author_openalex_author_id'), 'raw_author', ['openalex_author_id'], unique=True)
    op.create_index(op.f('ix_raw_author_orcid'), 'raw_author', ['orcid'], unique=False)
    op.create_index(op.f('ix_raw_author_processed_status'), 'raw_author', ['processed_status'], unique=False)
    op.create_index(op.f('ix_raw_author_raw_author_id'), 'raw_author', ['raw_author_id'], unique=False)
    op.create_index(op.f('ix_raw_author_std_author_id'), 'raw_author', ['std_author_id'], unique=False)
    op.create_table('raw_institution',
    sa.Column('raw_institution_id', sa.Integer(), nullable=False),
    sa.Column('openalex_institution_id', sa.String(length=50), nullable=False),
    sa.Column('raw_json', sa.Text(), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('country_code', sa.String(length=10), nullable=True),
    sa.Column('country_name', sa.String(length=100), nullable=True),
    sa.Column('ror', sa.String(length=50), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('processed_status', sa.String(length=20), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('error_info', sa.Text(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.Column('fetch_task_id', sa.Integer(), nullable=True),
    sa.Column('std_school_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['fetch_task_id'], ['sync_collect_task.task_id'], ),
    sa.PrimaryKeyConstraint('raw_institution_id')
    )
    op.create_index(op.f('ix_raw_institution_country_code'), 'raw_institution', ['country_code'], unique=False)
    op.create_index(op.f('ix_raw_institution_display_name'), 'raw_institution', ['display_name'], unique=False)
    op.create_index(op.f('ix_raw_institution_openalex_institution_id'), 'raw_institution', ['openalex_institution_id'], unique=True)
    op.create_index(op.f('ix_raw_institution_processed_status'), 'raw_institution', ['processed_status'], unique=False)
    op.create_index(op.f('ix_raw_institution_raw_institution_id'), 'raw_institution', ['raw_institution_id'], unique=False)
    op.create_index(op.f('ix_raw_institution_std_school_id'), 'raw_institution', ['std_school_id'], unique=False)
    op.create_table('rel_author_tech_belong',
    sa.Column('belong_id', sa.Integer(), nullable=False),
    sa.Column('openalex_author_id', sa.String(length=50), nullable=False),
    sa.Column('std_author_id', sa.Integer(), nullable=True),
    sa.Column('tech_element_id', sa.Integer(), nullable=False),
    sa.Column('source_venue_id', sa.Integer(), nullable=True),
    sa.Column('work_count_in_venue', sa.Integer(), nullable=True),
    sa.Column('first_work_year', sa.Integer(), nullable=True),
    sa.Column('last_work_year', sa.Integer(), nullable=True),
    sa.Column('source_task_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['source_task_id'], ['sync_collect_task.task_id'], ),
    sa.ForeignKeyConstraint(['source_venue_id'], ['config_venue.venue_id'], ),
    sa.ForeignKeyConstraint(['tech_element_id'], ['core_tech_element.tech_element_id'], ),
    sa.PrimaryKeyConstraint('belong_id')
    )
    op.create_index('ix_author_tech_author_tech', 'rel_author_tech_belong', ['openalex_author_id', 'tech_element_id'], unique=True)
    op.create_index(op.f('ix_rel_author_tech_belong_belong_id'), 'rel_author_tech_belong', ['belong_id'], unique=False)
    op.create_index(op.f('ix_rel_author_tech_belong_openalex_author_id'), 'rel_author_tech_belong', ['openalex_author_id'], unique=False)
    op.create_index(op.f('ix_rel_author_tech_belong_std_author_id'), 'rel_author_tech_belong', ['std_author_id'], unique=False)
    op.create_index(op.f('ix_rel_author_tech_belong_tech_element_id'), 'rel_author_tech_belong', ['tech_element_id'], unique=False)
    op.create_table('std_school',
    sa.Column('std_school_id', sa.Integer(), nullable=False),
    sa.Column('openalex_institution_id', sa.String(length=50), nullable=True),
    sa.Column('name_normalized', sa.String(length=255), nullable=False),
    sa.Column('name_aliases', sa.Text(), nullable=True),
    sa.Column('country_code', sa.String(length=10), nullable=True),
    sa.Column('country_name', sa.String(length=100), nullable=True),
    sa.Column('ror', sa.String(length=50), nullable=True),
    sa.Column('inst_type', sa.String(length=50), nullable=True),
    sa.Column('homepage_url', sa.String(length=500), nullable=True),
    sa.Column('confirm_status', sa.String(length=20), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=True),
    sa.Column('source_task_id', sa.Integer(), nullable=True),
    sa.Column('normalized_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['core_school.school_id'], ),
    sa.ForeignKeyConstraint(['source_task_id'], ['sync_collect_task.task_id'], ),
    sa.PrimaryKeyConstraint('std_school_id')
    )
    op.create_index(op.f('ix_std_school_confirm_status'), 'std_school', ['confirm_status'], unique=False)
    op.create_index(op.f('ix_std_school_country_code'), 'std_school', ['country_code'], unique=False)
    op.create_index(op.f('ix_std_school_name_normalized'), 'std_school', ['name_normalized'], unique=False)
    op.create_index(op.f('ix_std_school_openalex_institution_id'), 'std_school', ['openalex_institution_id'], unique=True)
    op.create_index(op.f('ix_std_school_ror'), 'std_school', ['ror'], unique=False)
    op.create_index(op.f('ix_std_school_school_id'), 'std_school', ['school_id'], unique=False)
    op.create_index(op.f('ix_std_school_std_school_id'), 'std_school', ['std_school_id'], unique=False)
    op.create_table('sync_venue_sub_task',
    sa.Column('sub_task_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('venue_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('time_window_start', sa.DateTime(), nullable=True),
    sa.Column('time_window_end', sa.DateTime(), nullable=True),
    sa.Column('estimated_works', sa.Integer(), nullable=True),
    sa.Column('works_fetched', sa.Integer(), nullable=True),
    sa.Column('authors_fetched', sa.Integer(), nullable=True),
    sa.Column('new_authors', sa.Integer(), nullable=True),
    sa.Column('updated_authors', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['sync_collect_task.task_id'], ),
    sa.ForeignKeyConstraint(['venue_id'], ['config_venue.venue_id'], ),
    sa.PrimaryKeyConstraint('sub_task_id')
    )
    op.create_index(op.f('ix_sync_venue_sub_task_status'), 'sync_venue_sub_task', ['status'], unique=False)
    op.create_index(op.f('ix_sync_venue_sub_task_sub_task_id'), 'sync_venue_sub_task', ['sub_task_id'], unique=False)
    op.create_index(op.f('ix_sync_venue_sub_task_task_id'), 'sync_venue_sub_task', ['task_id'], unique=False)
    op.create_index(op.f('ix_sync_venue_sub_task_venue_id'), 'sync_venue_sub_task', ['venue_id'], unique=False)
    op.create_table('data_publish_record',
    sa.Column('publish_id', sa.Integer(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('previous_version_id', sa.Integer(), nullable=True),
    sa.Column('operated_by', sa.Integer(), nullable=False),
    sa.Column('operated_at', sa.DateTime(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['operated_by'], ['iam_user_account.user_id'], ),
    sa.ForeignKeyConstraint(['previous_version_id'], ['data_version.version_id'], ),
    sa.ForeignKeyConstraint(['version_id'], ['data_version.version_id'], ),
    sa.PrimaryKeyConstraint('publish_id')
    )
    op.create_index(op.f('ix_data_publish_record_publish_id'), 'data_publish_record', ['publish_id'], unique=False)
    op.create_index(op.f('ix_data_publish_record_version_id'), 'data_publish_record', ['version_id'], unique=False)
    op.create_table('data_quality_summary',
    sa.Column('summary_id', sa.Integer(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('summary_date', sa.DateTime(), nullable=False),
    sa.Column('talent_total', sa.Integer(), nullable=True),
    sa.Column('talent_with_orcid', sa.Integer(), nullable=True),
    sa.Column('talent_with_affiliation', sa.Integer(), nullable=True),
    sa.Column('talent_with_works', sa.Integer(), nullable=True),
    sa.Column('talent_completeness_avg', sa.Integer(), nullable=True),
    sa.Column('school_total', sa.Integer(), nullable=True),
    sa.Column('school_with_ror', sa.Integer(), nullable=True),
    sa.Column('school_with_country', sa.Integer(), nullable=True),
    sa.Column('work_total', sa.Integer(), nullable=True),
    sa.Column('work_with_doi', sa.Integer(), nullable=True),
    sa.Column('tech_tag_total', sa.Integer(), nullable=True),
    sa.Column('tech_tag_confirmed', sa.Integer(), nullable=True),
    sa.Column('tech_tag_auto_identified', sa.Integer(), nullable=True),
    sa.Column('tech_tag_pending_confirm', sa.Integer(), nullable=True),
    sa.Column('issues_critical', sa.Integer(), nullable=True),
    sa.Column('issues_warning', sa.Integer(), nullable=True),
    sa.Column('issues_info', sa.Integer(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['version_id'], ['data_version.version_id'], ),
    sa.PrimaryKeyConstraint('summary_id')
    )
    op.create_index(op.f('ix_data_quality_summary_summary_date'), 'data_quality_summary', ['summary_date'], unique=False)
    op.create_index(op.f('ix_data_quality_summary_summary_id'), 'data_quality_summary', ['summary_id'], unique=False)
    op.create_index(op.f('ix_data_quality_summary_version_id'), 'data_quality_summary', ['version_id'], unique=False)
    op.create_table('raw_work',
    sa.Column('raw_work_id', sa.Integer(), nullable=False),
    sa.Column('openalex_work_id', sa.String(length=50), nullable=False),
    sa.Column('raw_json', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('doi', sa.String(length=200), nullable=True),
    sa.Column('publication_year', sa.Integer(), nullable=True),
    sa.Column('publication_date', sa.String(length=20), nullable=True),
    sa.Column('source_id', sa.String(length=50), nullable=True),
    sa.Column('source_name', sa.String(length=255), nullable=True),
    sa.Column('author_count', sa.Integer(), nullable=True),
    sa.Column('author_ids', sa.Text(), nullable=True),
    sa.Column('processed_status', sa.String(length=20), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('error_info', sa.Text(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.Column('fetch_task_id', sa.Integer(), nullable=True),
    sa.Column('sub_task_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['fetch_task_id'], ['sync_collect_task.task_id'], ),
    sa.ForeignKeyConstraint(['sub_task_id'], ['sync_venue_sub_task.sub_task_id'], ),
    sa.PrimaryKeyConstraint('raw_work_id')
    )
    op.create_index(op.f('ix_raw_work_doi'), 'raw_work', ['doi'], unique=False)
    op.create_index(op.f('ix_raw_work_openalex_work_id'), 'raw_work', ['openalex_work_id'], unique=True)
    op.create_index(op.f('ix_raw_work_processed_status'), 'raw_work', ['processed_status'], unique=False)
    op.create_index(op.f('ix_raw_work_publication_year'), 'raw_work', ['publication_year'], unique=False)
    op.create_index(op.f('ix_raw_work_raw_work_id'), 'raw_work', ['raw_work_id'], unique=False)
    op.create_index(op.f('ix_raw_work_source_id'), 'raw_work', ['source_id'], unique=False)
    op.create_table('std_author',
    sa.Column('std_author_id', sa.Integer(), nullable=False),
    sa.Column('openalex_author_id', sa.String(length=50), nullable=False),
    sa.Column('name_normalized', sa.String(length=255), nullable=False),
    sa.Column('name_original', sa.String(length=255), nullable=True),
    sa.Column('orcid', sa.String(length=50), nullable=True),
    sa.Column('works_count', sa.Integer(), nullable=True),
    sa.Column('cited_by_count', sa.Integer(), nullable=True),
    sa.Column('h_index', sa.Integer(), nullable=True),
    sa.Column('i10_index', sa.Integer(), nullable=True),
    sa.Column('std_school_id', sa.Integer(), nullable=True),
    sa.Column('raw_institution_name', sa.String(length=255), nullable=True),
    sa.Column('raw_institution_id', sa.String(length=50), nullable=True),
    sa.Column('confirm_status', sa.String(length=20), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('openalex_topics', sa.JSON(), nullable=True),
    sa.Column('cs_concepts_score', sa.Float(), nullable=True),
    sa.Column('source_task_id', sa.Integer(), nullable=True),
    sa.Column('normalized_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['source_task_id'], ['sync_collect_task.task_id'], ),
    sa.ForeignKeyConstraint(['std_school_id'], ['std_school.std_school_id'], ),
    sa.PrimaryKeyConstraint('std_author_id')
    )
    op.create_index(op.f('ix_std_author_confirm_status'), 'std_author', ['confirm_status'], unique=False)
    op.create_index(op.f('ix_std_author_name_normalized'), 'std_author', ['name_normalized'], unique=False)
    op.create_index(op.f('ix_std_author_openalex_author_id'), 'std_author', ['openalex_author_id'], unique=True)
    op.create_index(op.f('ix_std_author_orcid'), 'std_author', ['orcid'], unique=False)
    op.create_index(op.f('ix_std_author_std_author_id'), 'std_author', ['std_author_id'], unique=False)
    op.create_index(op.f('ix_std_author_std_school_id'), 'std_author', ['std_school_id'], unique=False)
    op.create_table('std_school_alias',
    sa.Column('alias_id', sa.Integer(), nullable=False),
    sa.Column('std_school_id', sa.Integer(), nullable=False),
    sa.Column('alias_name', sa.String(length=255), nullable=False),
    sa.Column('alias_type', sa.String(length=30), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['std_school_id'], ['std_school.std_school_id'], ),
    sa.PrimaryKeyConstraint('alias_id')
    )
    op.create_index('ix_school_alias_name', 'std_school_alias', ['alias_name'], unique=False)
    op.create_index(op.f('ix_std_school_alias_alias_id'), 'std_school_alias', ['alias_id'], unique=False)
    op.create_index(op.f('ix_std_school_alias_alias_name'), 'std_school_alias', ['alias_name'], unique=False)
    op.create_index(op.f('ix_std_school_alias_std_school_id'), 'std_school_alias', ['std_school_id'], unique=False)
    op.create_table('core_talent',
    sa.Column('talent_id', sa.Integer(), nullable=False),
    sa.Column('std_author_id', sa.Integer(), nullable=True),
    sa.Column('source_type', sa.String(length=50), nullable=True),
    sa.Column('source_record_id', sa.String(length=100), nullable=True),
    sa.Column('last_sync_batch_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('name_en', sa.String(length=255), nullable=True),
    sa.Column('orcid', sa.String(length=50), nullable=True),
    sa.Column('school_id', sa.Integer(), nullable=True),
    sa.Column('current_title', sa.String(length=255), nullable=True),
    sa.Column('role_type', sa.String(length=20), nullable=False),
    sa.Column('role_confidence', sa.Float(), nullable=True),
    sa.Column('topic_tags', sa.JSON(), nullable=True),
    sa.Column('openalex_topics', sa.JSON(), nullable=True),
    sa.Column('research_interests', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('works_count', sa.Integer(), nullable=True),
    sa.Column('cited_by_count', sa.Integer(), nullable=True),
    sa.Column('h_index', sa.Integer(), nullable=True),
    sa.Column('latest_active_year', sa.Integer(), nullable=True),
    sa.Column('visibility_status', sa.String(length=20), nullable=False),
    sa.Column('is_visible', sa.Boolean(), nullable=False),
    sa.Column('unified_person_id', sa.String(length=100), nullable=True),
    sa.Column('department_name', sa.String(length=255), nullable=True),
    sa.Column('lab_name', sa.String(length=255), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['core_school.school_id'], ),
    sa.ForeignKeyConstraint(['std_author_id'], ['std_author.std_author_id'], ),
    sa.PrimaryKeyConstraint('talent_id')
    )
    op.create_index(op.f('ix_core_talent_name'), 'core_talent', ['name'], unique=False)
    op.create_index(op.f('ix_core_talent_orcid'), 'core_talent', ['orcid'], unique=False)
    op.create_index(op.f('ix_core_talent_role_type'), 'core_talent', ['role_type'], unique=False)
    op.create_index(op.f('ix_core_talent_school_id'), 'core_talent', ['school_id'], unique=False)
    op.create_index(op.f('ix_core_talent_source_record_id'), 'core_talent', ['source_record_id'], unique=False)
    op.create_index('ix_core_talent_source_record_id_unique', 'core_talent', ['source_record_id'], unique=True, postgresql_where=sa.text('source_record_id IS NOT NULL'))
    op.create_index(op.f('ix_core_talent_std_author_id'), 'core_talent', ['std_author_id'], unique=False)
    op.create_index(op.f('ix_core_talent_talent_id'), 'core_talent', ['talent_id'], unique=False)
    op.create_table('core_collaboration',
    sa.Column('collaboration_id', sa.Integer(), nullable=False),
    sa.Column('talent_id_1', sa.Integer(), nullable=False),
    sa.Column('talent_id_2', sa.Integer(), nullable=False),
    sa.Column('collaboration_count', sa.Integer(), nullable=False),
    sa.Column('first_collaboration_year', sa.Integer(), nullable=True),
    sa.Column('last_collaboration_year', sa.Integer(), nullable=True),
    sa.Column('source_batch_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['talent_id_1'], ['core_talent.talent_id'], ),
    sa.ForeignKeyConstraint(['talent_id_2'], ['core_talent.talent_id'], ),
    sa.PrimaryKeyConstraint('collaboration_id'),
    sa.UniqueConstraint('talent_id_1', 'talent_id_2', name='uq_collaboration_pair')
    )
    op.create_index(op.f('ix_core_collaboration_collaboration_id'), 'core_collaboration', ['collaboration_id'], unique=False)
    op.create_index(op.f('ix_core_collaboration_talent_id_1'), 'core_collaboration', ['talent_id_1'], unique=False)
    op.create_index(op.f('ix_core_collaboration_talent_id_2'), 'core_collaboration', ['talent_id_2'], unique=False)
    op.create_table('core_role_profile',
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('talent_id', sa.Integer(), nullable=False),
    sa.Column('role_type', sa.String(length=20), nullable=False),
    sa.Column('role_confidence', sa.Float(), nullable=True),
    sa.Column('role_reason', sa.Text(), nullable=True),
    sa.Column('identification_method', sa.String(length=50), nullable=True),
    sa.Column('identified_at', sa.String(length=50), nullable=True),
    sa.Column('position_title', sa.String(length=255), nullable=True),
    sa.Column('academic_age', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['talent_id'], ['core_talent.talent_id'], ),
    sa.PrimaryKeyConstraint('profile_id'),
    sa.UniqueConstraint('talent_id')
    )
    op.create_index(op.f('ix_core_role_profile_profile_id'), 'core_role_profile', ['profile_id'], unique=False)
    op.create_table('core_selected_work',
    sa.Column('work_id', sa.Integer(), nullable=False),
    sa.Column('talent_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('publication_year', sa.Integer(), nullable=True),
    sa.Column('venue_name', sa.String(length=255), nullable=True),
    sa.Column('citation_count', sa.Integer(), nullable=True),
    sa.Column('source_work_id', sa.String(length=100), nullable=True),
    sa.Column('doi', sa.String(length=100), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['talent_id'], ['core_talent.talent_id'], ),
    sa.PrimaryKeyConstraint('work_id')
    )
    op.create_index(op.f('ix_core_selected_work_talent_id'), 'core_selected_work', ['talent_id'], unique=False)
    op.create_index(op.f('ix_core_selected_work_work_id'), 'core_selected_work', ['work_id'], unique=False)
    op.create_table('core_talent_tech_tag',
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('talent_id', sa.Integer(), nullable=False),
    sa.Column('tech_element_id', sa.Integer(), nullable=False),
    sa.Column('tech_direction_id', sa.Integer(), nullable=False),
    sa.Column('tag_level', sa.String(length=20), nullable=False),
    sa.Column('tag_source', sa.String(length=20), nullable=False),
    sa.Column('confirm_status', sa.String(length=20), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['talent_id'], ['core_talent.talent_id'], ),
    sa.ForeignKeyConstraint(['tech_direction_id'], ['core_tech_direction.tech_direction_id'], ),
    sa.ForeignKeyConstraint(['tech_element_id'], ['core_tech_element.tech_element_id'], ),
    sa.PrimaryKeyConstraint('tag_id'),
    sa.UniqueConstraint('talent_id', 'tech_direction_id', name='uq_talent_tech_direction')
    )
    op.create_index(op.f('ix_core_talent_tech_tag_tag_id'), 'core_talent_tech_tag', ['tag_id'], unique=False)
    op.create_index(op.f('ix_core_talent_tech_tag_talent_id'), 'core_talent_tech_tag', ['talent_id'], unique=False)
    op.create_index(op.f('ix_core_talent_tech_tag_tech_direction_id'), 'core_talent_tech_tag', ['tech_direction_id'], unique=False)
    op.create_index(op.f('ix_core_talent_tech_tag_tech_element_id'), 'core_talent_tech_tag', ['tech_element_id'], unique=False)
    op.create_table('core_work_author',
    sa.Column('work_author_id', sa.Integer(), nullable=False),
    sa.Column('source_work_id', sa.String(length=100), nullable=False),
    sa.Column('work_title', sa.String(length=500), nullable=True),
    sa.Column('publication_year', sa.Integer(), nullable=True),
    sa.Column('talent_id', sa.Integer(), nullable=True),
    sa.Column('author_position', sa.Integer(), nullable=True),
    sa.Column('author_name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['talent_id'], ['core_talent.talent_id'], ),
    sa.PrimaryKeyConstraint('work_author_id')
    )
    op.create_index(op.f('ix_core_work_author_source_work_id'), 'core_work_author', ['source_work_id'], unique=False)
    op.create_index(op.f('ix_core_work_author_talent_id'), 'core_work_author', ['talent_id'], unique=False)
    op.create_index(op.f('ix_core_work_author_work_author_id'), 'core_work_author', ['work_author_id'], unique=False)
    op.create_table('iam_favorite_talent',
    sa.Column('favorite_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('talent_id', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('followup_status', sa.String(length=30), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['talent_id'], ['core_talent.talent_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['iam_user_account.user_id'], ),
    sa.PrimaryKeyConstraint('favorite_id'),
    sa.UniqueConstraint('user_id', 'talent_id', name='uq_user_favorite_talent')
    )
    op.create_index(op.f('ix_iam_favorite_talent_favorite_id'), 'iam_favorite_talent', ['favorite_id'], unique=False)
    op.create_index(op.f('ix_iam_favorite_talent_talent_id'), 'iam_favorite_talent', ['talent_id'], unique=False)
    op.create_index(op.f('ix_iam_favorite_talent_user_id'), 'iam_favorite_talent', ['user_id'], unique=False)
    op.create_table('iam_talent_pool_member',
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('pool_id', sa.Integer(), nullable=False),
    sa.Column('talent_id', sa.Integer(), nullable=False),
    sa.Column('added_by', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['pool_id'], ['iam_talent_pool.pool_id'], ),
    sa.ForeignKeyConstraint(['talent_id'], ['core_talent.talent_id'], ),
    sa.PrimaryKeyConstraint('member_id'),
    sa.UniqueConstraint('pool_id', 'talent_id', name='uq_pool_talent')
    )
    op.create_index(op.f('ix_iam_talent_pool_member_member_id'), 'iam_talent_pool_member', ['member_id'], unique=False)
    op.create_index(op.f('ix_iam_talent_pool_member_pool_id'), 'iam_talent_pool_member', ['pool_id'], unique=False)
    op.create_index(op.f('ix_iam_talent_pool_member_talent_id'), 'iam_talent_pool_member', ['talent_id'], unique=False)
    op.drop_index('ix_work_author_author', table_name='openalex_work_author')
    op.drop_index('ix_work_author_work', table_name='openalex_work_author')
    op.drop_table('openalex_work_author')
    op.drop_index('ix_openalex_inst_country', table_name='openalex_institution')
    op.drop_index('ix_openalex_inst_name', table_name='openalex_institution')
    op.drop_index('ix_openalex_inst_type', table_name='openalex_institution')
    op.drop_table('openalex_institution')
    op.drop_table('openalex_publisher')
    op.drop_table('openalex_funder')
    op.drop_index('ix_work_concept_concept', table_name='openalex_work_concept')
    op.drop_index('ix_work_concept_work', table_name='openalex_work_concept')
    op.drop_table('openalex_work_concept')
    op.drop_index('ix_openalex_author_name', table_name='openalex_author')
    op.drop_index('ix_openalex_author_orcid', table_name='openalex_author')
    op.drop_index('ix_openalex_author_works', table_name='openalex_author')
    op.drop_table('openalex_author')
    op.drop_index('ix_openalex_work_doi', table_name='openalex_work')
    op.drop_index('ix_openalex_work_source', table_name='openalex_work')
    op.drop_index('ix_openalex_work_title', table_name='openalex_work')
    op.drop_index('ix_openalex_work_type', table_name='openalex_work')
    op.drop_index('ix_openalex_work_year', table_name='openalex_work')
    op.drop_table('openalex_work')
    op.drop_index('ix_openalex_source_issn', table_name='openalex_source')
    op.drop_index('ix_openalex_source_name', table_name='openalex_source')
    op.drop_index('ix_openalex_source_type', table_name='openalex_source')
    op.drop_table('openalex_source')
    op.drop_index('ix_openalex_concept_level', table_name='openalex_concept')
    op.drop_index('ix_openalex_concept_name', table_name='openalex_concept')
    op.drop_table('openalex_concept')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('openalex_concept',
    sa.Column('concept_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('display_name', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('level', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('works_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('cited_by_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('wikidata', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('image_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('ancestors', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('related_concepts', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('counts_by_year', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('raw_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('concept_id', name='openalex_concept_pkey')
    )
    op.create_index('ix_openalex_concept_name', 'openalex_concept', ['display_name'], unique=False)
    op.create_index('ix_openalex_concept_level', 'openalex_concept', ['level'], unique=False)
    op.create_table('openalex_source',
    sa.Column('source_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('display_name', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('issn', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('issn_l', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('works_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('cited_by_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('h_index', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_oa', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_in_doaj', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('host_organization', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('host_organization_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('country_codes', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('apc_prices', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('raw_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('source_id', name='openalex_source_pkey')
    )
    op.create_index('ix_openalex_source_type', 'openalex_source', ['type'], unique=False)
    op.create_index('ix_openalex_source_name', 'openalex_source', ['display_name'], unique=False)
    op.create_index('ix_openalex_source_issn', 'openalex_source', ['issn_l'], unique=False)
    op.create_table('openalex_work',
    sa.Column('work_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('title', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('display_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('doi', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('publication_year', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('publication_date', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('cited_by_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_retracted', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_paratext', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('language', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('source_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('source_name', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('author_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('author_ids', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('institution_ids', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('concepts', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('keywords', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('referenced_works', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('related_works', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('abstract_inverted_index', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('open_access', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('raw_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('work_id', name='openalex_work_pkey')
    )
    op.create_index('ix_openalex_work_year', 'openalex_work', ['publication_year'], unique=False)
    op.create_index('ix_openalex_work_type', 'openalex_work', ['type'], unique=False)
    op.create_index('ix_openalex_work_title', 'openalex_work', ['title'], unique=False)
    op.create_index('ix_openalex_work_source', 'openalex_work', ['source_id'], unique=False)
    op.create_index('ix_openalex_work_doi', 'openalex_work', ['doi'], unique=False)
    op.create_table('openalex_author',
    sa.Column('author_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('display_name', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('display_name_alternatives', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('orcid', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('works_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('cited_by_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('h_index', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('i10_index', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('institution_ids', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('last_known_institution', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('topics', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('x_concepts', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('counts_by_year', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('raw_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('author_id', name='openalex_author_pkey')
    )
    op.create_index('ix_openalex_author_works', 'openalex_author', ['works_count'], unique=False)
    op.create_index('ix_openalex_author_orcid', 'openalex_author', ['orcid'], unique=False)
    op.create_index('ix_openalex_author_name', 'openalex_author', ['display_name'], unique=False)
    op.create_table('openalex_work_concept',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('work_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('concept_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='openalex_work_concept_pkey')
    )
    op.create_index('ix_work_concept_work', 'openalex_work_concept', ['work_id'], unique=False)
    op.create_index('ix_work_concept_concept', 'openalex_work_concept', ['concept_id'], unique=False)
    op.create_table('openalex_funder',
    sa.Column('funder_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('display_name', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('alternate_titles', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('country_code', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('works_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('cited_by_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('awards_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('homepage_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('raw_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('funder_id', name='openalex_funder_pkey')
    )
    op.create_table('openalex_publisher',
    sa.Column('publisher_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('display_name', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('alternate_titles', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('hierarchy_level', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('parent_publisher', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('country_codes', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('works_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('cited_by_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('h_index', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('homepage_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('raw_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('publisher_id', name='openalex_publisher_pkey')
    )
    op.create_table('openalex_institution',
    sa.Column('institution_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('display_name', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('display_name_alternatives', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('country_code', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('country_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('ror', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('works_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('cited_by_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('h_index', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('homepage_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('image_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('latitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('longitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('geo', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('associated_institutions', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('counts_by_year', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('raw_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('institution_id', name='openalex_institution_pkey')
    )
    op.create_index('ix_openalex_inst_type', 'openalex_institution', ['type'], unique=False)
    op.create_index('ix_openalex_inst_name', 'openalex_institution', ['display_name'], unique=False)
    op.create_index('ix_openalex_inst_country', 'openalex_institution', ['country_code'], unique=False)
    op.create_table('openalex_work_author',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('work_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('author_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('author_position', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('is_corresponding', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('affiliation_raw', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('affiliation_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='openalex_work_author_pkey')
    )
    op.create_index('ix_work_author_work', 'openalex_work_author', ['work_id'], unique=False)
    op.create_index('ix_work_author_author', 'openalex_work_author', ['author_id'], unique=False)
    op.drop_index(op.f('ix_iam_talent_pool_member_talent_id'), table_name='iam_talent_pool_member')
    op.drop_index(op.f('ix_iam_talent_pool_member_pool_id'), table_name='iam_talent_pool_member')
    op.drop_index(op.f('ix_iam_talent_pool_member_member_id'), table_name='iam_talent_pool_member')
    op.drop_table('iam_talent_pool_member')
    op.drop_index(op.f('ix_iam_favorite_talent_user_id'), table_name='iam_favorite_talent')
    op.drop_index(op.f('ix_iam_favorite_talent_talent_id'), table_name='iam_favorite_talent')
    op.drop_index(op.f('ix_iam_favorite_talent_favorite_id'), table_name='iam_favorite_talent')
    op.drop_table('iam_favorite_talent')
    op.drop_index(op.f('ix_core_work_author_work_author_id'), table_name='core_work_author')
    op.drop_index(op.f('ix_core_work_author_talent_id'), table_name='core_work_author')
    op.drop_index(op.f('ix_core_work_author_source_work_id'), table_name='core_work_author')
    op.drop_table('core_work_author')
    op.drop_index(op.f('ix_core_talent_tech_tag_tech_element_id'), table_name='core_talent_tech_tag')
    op.drop_index(op.f('ix_core_talent_tech_tag_tech_direction_id'), table_name='core_talent_tech_tag')
    op.drop_index(op.f('ix_core_talent_tech_tag_talent_id'), table_name='core_talent_tech_tag')
    op.drop_index(op.f('ix_core_talent_tech_tag_tag_id'), table_name='core_talent_tech_tag')
    op.drop_table('core_talent_tech_tag')
    op.drop_index(op.f('ix_core_selected_work_work_id'), table_name='core_selected_work')
    op.drop_index(op.f('ix_core_selected_work_talent_id'), table_name='core_selected_work')
    op.drop_table('core_selected_work')
    op.drop_index(op.f('ix_core_role_profile_profile_id'), table_name='core_role_profile')
    op.drop_table('core_role_profile')
    op.drop_index(op.f('ix_core_collaboration_talent_id_2'), table_name='core_collaboration')
    op.drop_index(op.f('ix_core_collaboration_talent_id_1'), table_name='core_collaboration')
    op.drop_index(op.f('ix_core_collaboration_collaboration_id'), table_name='core_collaboration')
    op.drop_table('core_collaboration')
    op.drop_index(op.f('ix_core_talent_talent_id'), table_name='core_talent')
    op.drop_index(op.f('ix_core_talent_std_author_id'), table_name='core_talent')
    op.drop_index('ix_core_talent_source_record_id_unique', table_name='core_talent', postgresql_where=sa.text('source_record_id IS NOT NULL'))
    op.drop_index(op.f('ix_core_talent_source_record_id'), table_name='core_talent')
    op.drop_index(op.f('ix_core_talent_school_id'), table_name='core_talent')
    op.drop_index(op.f('ix_core_talent_role_type'), table_name='core_talent')
    op.drop_index(op.f('ix_core_talent_orcid'), table_name='core_talent')
    op.drop_index(op.f('ix_core_talent_name'), table_name='core_talent')
    op.drop_table('core_talent')
    op.drop_index(op.f('ix_std_school_alias_std_school_id'), table_name='std_school_alias')
    op.drop_index(op.f('ix_std_school_alias_alias_name'), table_name='std_school_alias')
    op.drop_index(op.f('ix_std_school_alias_alias_id'), table_name='std_school_alias')
    op.drop_index('ix_school_alias_name', table_name='std_school_alias')
    op.drop_table('std_school_alias')
    op.drop_index(op.f('ix_std_author_std_school_id'), table_name='std_author')
    op.drop_index(op.f('ix_std_author_std_author_id'), table_name='std_author')
    op.drop_index(op.f('ix_std_author_orcid'), table_name='std_author')
    op.drop_index(op.f('ix_std_author_openalex_author_id'), table_name='std_author')
    op.drop_index(op.f('ix_std_author_name_normalized'), table_name='std_author')
    op.drop_index(op.f('ix_std_author_confirm_status'), table_name='std_author')
    op.drop_table('std_author')
    op.drop_index(op.f('ix_raw_work_source_id'), table_name='raw_work')
    op.drop_index(op.f('ix_raw_work_raw_work_id'), table_name='raw_work')
    op.drop_index(op.f('ix_raw_work_publication_year'), table_name='raw_work')
    op.drop_index(op.f('ix_raw_work_processed_status'), table_name='raw_work')
    op.drop_index(op.f('ix_raw_work_openalex_work_id'), table_name='raw_work')
    op.drop_index(op.f('ix_raw_work_doi'), table_name='raw_work')
    op.drop_table('raw_work')
    op.drop_index(op.f('ix_data_quality_summary_version_id'), table_name='data_quality_summary')
    op.drop_index(op.f('ix_data_quality_summary_summary_id'), table_name='data_quality_summary')
    op.drop_index(op.f('ix_data_quality_summary_summary_date'), table_name='data_quality_summary')
    op.drop_table('data_quality_summary')
    op.drop_index(op.f('ix_data_publish_record_version_id'), table_name='data_publish_record')
    op.drop_index(op.f('ix_data_publish_record_publish_id'), table_name='data_publish_record')
    op.drop_table('data_publish_record')
    op.drop_index(op.f('ix_sync_venue_sub_task_venue_id'), table_name='sync_venue_sub_task')
    op.drop_index(op.f('ix_sync_venue_sub_task_task_id'), table_name='sync_venue_sub_task')
    op.drop_index(op.f('ix_sync_venue_sub_task_sub_task_id'), table_name='sync_venue_sub_task')
    op.drop_index(op.f('ix_sync_venue_sub_task_status'), table_name='sync_venue_sub_task')
    op.drop_table('sync_venue_sub_task')
    op.drop_index(op.f('ix_std_school_std_school_id'), table_name='std_school')
    op.drop_index(op.f('ix_std_school_school_id'), table_name='std_school')
    op.drop_index(op.f('ix_std_school_ror'), table_name='std_school')
    op.drop_index(op.f('ix_std_school_openalex_institution_id'), table_name='std_school')
    op.drop_index(op.f('ix_std_school_name_normalized'), table_name='std_school')
    op.drop_index(op.f('ix_std_school_country_code'), table_name='std_school')
    op.drop_index(op.f('ix_std_school_confirm_status'), table_name='std_school')
    op.drop_table('std_school')
    op.drop_index(op.f('ix_rel_author_tech_belong_tech_element_id'), table_name='rel_author_tech_belong')
    op.drop_index(op.f('ix_rel_author_tech_belong_std_author_id'), table_name='rel_author_tech_belong')
    op.drop_index(op.f('ix_rel_author_tech_belong_openalex_author_id'), table_name='rel_author_tech_belong')
    op.drop_index(op.f('ix_rel_author_tech_belong_belong_id'), table_name='rel_author_tech_belong')
    op.drop_index('ix_author_tech_author_tech', table_name='rel_author_tech_belong')
    op.drop_table('rel_author_tech_belong')
    op.drop_index(op.f('ix_raw_institution_std_school_id'), table_name='raw_institution')
    op.drop_index(op.f('ix_raw_institution_raw_institution_id'), table_name='raw_institution')
    op.drop_index(op.f('ix_raw_institution_processed_status'), table_name='raw_institution')
    op.drop_index(op.f('ix_raw_institution_openalex_institution_id'), table_name='raw_institution')
    op.drop_index(op.f('ix_raw_institution_display_name'), table_name='raw_institution')
    op.drop_index(op.f('ix_raw_institution_country_code'), table_name='raw_institution')
    op.drop_table('raw_institution')
    op.drop_index(op.f('ix_raw_author_std_author_id'), table_name='raw_author')
    op.drop_index(op.f('ix_raw_author_raw_author_id'), table_name='raw_author')
    op.drop_index(op.f('ix_raw_author_processed_status'), table_name='raw_author')
    op.drop_index(op.f('ix_raw_author_orcid'), table_name='raw_author')
    op.drop_index(op.f('ix_raw_author_openalex_author_id'), table_name='raw_author')
    op.drop_index(op.f('ix_raw_author_last_known_institution_id'), table_name='raw_author')
    op.drop_index(op.f('ix_raw_author_display_name'), table_name='raw_author')
    op.drop_table('raw_author')
    op.drop_index(op.f('ix_data_version_version_id'), table_name='data_version')
    op.drop_index(op.f('ix_data_version_version_code'), table_name='data_version')
    op.drop_index(op.f('ix_data_version_is_active'), table_name='data_version')
    op.drop_table('data_version')
    op.drop_index(op.f('ix_sync_collect_task_tech_element_id'), table_name='sync_collect_task')
    op.drop_index(op.f('ix_sync_collect_task_task_id'), table_name='sync_collect_task')
    op.drop_index(op.f('ix_sync_collect_task_task_code'), table_name='sync_collect_task')
    op.drop_index(op.f('ix_sync_collect_task_status'), table_name='sync_collect_task')
    op.drop_table('sync_collect_task')
    op.drop_index(op.f('ix_sync_collect_strategy_strategy_id'), table_name='sync_collect_strategy')
    op.drop_index(op.f('ix_sync_collect_strategy_strategy_code'), table_name='sync_collect_strategy')
    op.drop_table('sync_collect_strategy')
    op.drop_index(op.f('ix_sync_collect_scope_scope_id'), table_name='sync_collect_scope')
    op.drop_index(op.f('ix_sync_collect_scope_scope_code'), table_name='sync_collect_scope')
    op.drop_table('sync_collect_scope')
    op.drop_index(op.f('ix_stat_school_snapshot_stat_version'), table_name='stat_school_snapshot')
    op.drop_index(op.f('ix_stat_school_snapshot_snapshot_id'), table_name='stat_school_snapshot')
    op.drop_index(op.f('ix_stat_school_snapshot_school_id'), table_name='stat_school_snapshot')
    op.drop_table('stat_school_snapshot')
    op.drop_index(op.f('ix_iam_user_school_scope_user_id'), table_name='iam_user_school_scope')
    op.drop_index(op.f('ix_iam_user_school_scope_scope_id'), table_name='iam_user_school_scope')
    op.drop_table('iam_user_school_scope')
    op.drop_index(op.f('ix_iam_talent_pool_pool_id'), table_name='iam_talent_pool')
    op.drop_index(op.f('ix_iam_talent_pool_owner_user_id'), table_name='iam_talent_pool')
    op.drop_table('iam_talent_pool')
    op.drop_index(op.f('ix_data_correction_record_target_type'), table_name='data_correction_record')
    op.drop_index(op.f('ix_data_correction_record_target_id'), table_name='data_correction_record')
    op.drop_index(op.f('ix_data_correction_record_correction_id'), table_name='data_correction_record')
    op.drop_table('data_correction_record')
    op.drop_index(op.f('ix_core_tech_direction_tech_element_id'), table_name='core_tech_direction')
    op.drop_index(op.f('ix_core_tech_direction_tech_direction_id'), table_name='core_tech_direction')
    op.drop_table('core_tech_direction')
    op.drop_index(op.f('ix_core_school_alias_school_id'), table_name='core_school_alias')
    op.drop_index(op.f('ix_core_school_alias_alias_name'), table_name='core_school_alias')
    op.drop_index(op.f('ix_core_school_alias_alias_id'), table_name='core_school_alias')
    op.drop_table('core_school_alias')
    op.drop_index(op.f('ix_config_venue_tech_binding_venue_id'), table_name='config_venue_tech_binding')
    op.drop_index(op.f('ix_config_venue_tech_binding_tech_element_id'), table_name='config_venue_tech_binding')
    op.drop_index(op.f('ix_config_venue_tech_binding_binding_id'), table_name='config_venue_tech_binding')
    op.drop_table('config_venue_tech_binding')
    op.drop_index(op.f('ix_sync_batch_status'), table_name='sync_batch')
    op.drop_index(op.f('ix_sync_batch_batch_id'), table_name='sync_batch')
    op.drop_index(op.f('ix_sync_batch_batch_code'), table_name='sync_batch')
    op.drop_table('sync_batch')
    op.drop_index(op.f('ix_stat_overview_snapshot_stat_version'), table_name='stat_overview_snapshot')
    op.drop_index(op.f('ix_stat_overview_snapshot_snapshot_id'), table_name='stat_overview_snapshot')
    op.drop_table('stat_overview_snapshot')
    op.drop_index(op.f('ix_search_talent_document_talent_id'), table_name='search_talent_document')
    op.drop_index(op.f('ix_search_talent_document_school_id'), table_name='search_talent_document')
    op.drop_index(op.f('ix_search_talent_document_role_type'), table_name='search_talent_document')
    op.drop_index(op.f('ix_search_talent_document_is_active'), table_name='search_talent_document')
    op.drop_index(op.f('ix_search_talent_document_document_id'), table_name='search_talent_document')
    op.drop_index(op.f('ix_search_talent_document_country_code'), table_name='search_talent_document')
    op.drop_table('search_talent_document')
    op.drop_index(op.f('ix_iam_user_account_username'), table_name='iam_user_account')
    op.drop_index(op.f('ix_iam_user_account_user_id'), table_name='iam_user_account')
    op.drop_index(op.f('ix_iam_user_account_email'), table_name='iam_user_account')
    op.drop_table('iam_user_account')
    op.drop_index(op.f('ix_core_tech_element_tech_element_id'), table_name='core_tech_element')
    op.drop_table('core_tech_element')
    op.drop_index('ix_core_school_source_record_id_unique', table_name='core_school', postgresql_where=sa.text('source_record_id IS NOT NULL'))
    op.drop_index(op.f('ix_core_school_source_record_id'), table_name='core_school')
    op.drop_index(op.f('ix_core_school_school_name'), table_name='core_school')
    op.drop_index(op.f('ix_core_school_school_id'), table_name='core_school')
    op.drop_index(op.f('ix_core_school_is_top_school'), table_name='core_school')
    op.drop_index(op.f('ix_core_school_country_code'), table_name='core_school')
    op.drop_table('core_school')
    op.drop_index(op.f('ix_config_venue_venue_id'), table_name='config_venue')
    op.drop_index(op.f('ix_config_venue_venue_code'), table_name='config_venue')
    op.drop_index(op.f('ix_config_venue_openalex_source_id'), table_name='config_venue')
    op.drop_table('config_venue')
    op.drop_index(op.f('ix_audit_operation_log_user_id'), table_name='audit_operation_log')
    op.drop_index(op.f('ix_audit_operation_log_resource_type'), table_name='audit_operation_log')
    op.drop_index(op.f('ix_audit_operation_log_request_id'), table_name='audit_operation_log')
    op.drop_index(op.f('ix_audit_operation_log_log_id'), table_name='audit_operation_log')
    op.drop_index(op.f('ix_audit_operation_log_event_type'), table_name='audit_operation_log')
    op.drop_index(op.f('ix_audit_operation_log_event_time'), table_name='audit_operation_log')
    op.drop_table('audit_operation_log')
    # ### end Alembic commands ###
